const STORAGE='document-compliance-vault-v1';
const DEMO_DOCS=[
  {id:'DOC-9001',loadId:'BH-1042',carrier:'Lakefront Logistics',customer:'Blue River Foods',docType:'rate con',status:'verified',required:'yes',dueHours:0,ageHours:6,expiresInDays:120,insuranceValue:0,owner:'broker ops',notes:'Signed rate confirmation saved to mock vault.'},
  {id:'DOC-9002',loadId:'BH-1042',carrier:'Lakefront Logistics',customer:'Blue River Foods',docType:'POD',status:'missing',required:'yes',dueHours:18,ageHours:30,expiresInDays:365,insuranceValue:0,owner:'carrier rep',notes:'Delivery completed; POD chase needed before invoice.'},
  {id:'DOC-9003',loadId:'BH-1048',carrier:'Ozark Freight',customer:'Ozark Retail',docType:'COI',status:'expiring',required:'yes',dueHours:0,ageHours:80,expiresInDays:9,insuranceValue:750000,owner:'compliance',notes:'COI below preferred threshold and expires soon.'},
  {id:'DOC-9004',loadId:'BH-1051',carrier:'Summit Linehaul',customer:'Summit Packaging',docType:'W9',status:'verified',required:'yes',dueHours:0,ageHours:300,expiresInDays:365,insuranceValue:0,owner:'accounting',notes:'W9 verified for payment setup.'},
  {id:'DOC-9005',loadId:'BH-1051',carrier:'Summit Linehaul',customer:'Summit Packaging',docType:'BOL',status:'review',required:'yes',dueHours:4,ageHours:20,expiresInDays:365,insuranceValue:0,owner:'broker ops',notes:'BOL received with timestamp gap; needs human check.'},
  {id:'DOC-9006',loadId:'BH-1055',carrier:'River City Supply Chain',customer:'River City Supply',docType:'carrier packet',status:'missing',required:'yes',dueHours:2,ageHours:12,expiresInDays:365,insuranceValue:0,owner:'carrier sales',notes:'Carrier packet incomplete before tender use.'}
];
const DEFAULTS={theme:'dark',missingPenalty:18,expiringSoonDays:14,podChaseHours:24,coiMinInsurance:1000000,reviewStance:'balanced',docs:DEMO_DOCS};
const $=id=>document.getElementById(id); const num=v=>Number(v)||0; const clone=v=>JSON.parse(JSON.stringify(v)); const pct=n=>`${Math.round(num(n))}%`; const money=n=>'$'+Math.round(num(n)).toLocaleString();
let state=loadState();
function loadState(){try{return {...clone(DEFAULTS),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function escapeAttr(v){return String(v??'').replace(/"/g,'&quot;');}
function docAudit(d){
  const strict=state.reviewStance==='strict'?1.25:state.reviewStance==='cash-first'?1.12:1;
  let penalty=0; const blockers=[];
  if(d.required==='yes'&&d.status==='missing'){penalty+=num(state.missingPenalty)*strict; blockers.push('required document missing');}
  if(d.status==='review'){penalty+=10*strict; blockers.push('human review needed');}
  if(d.status==='expiring'||num(d.expiresInDays)<=num(state.expiringSoonDays)){penalty+=12*strict; blockers.push('document expiring soon');}
  if(d.docType==='POD'&&num(d.ageHours)>num(state.podChaseHours)&&d.status!=='verified'){penalty+=16*strict; blockers.push('POD chase clock exceeded');}
  if(d.docType==='COI'&&num(d.insuranceValue)>0&&num(d.insuranceValue)<num(state.coiMinInsurance)){penalty+=14*strict; blockers.push('COI insurance below threshold');}
  if(/packet|W9|COI/i.test(d.docType)&&d.status!=='verified') {penalty+=7*strict; blockers.push('carrier compliance not clean');}
  const score=Math.max(0,Math.min(100,Math.round(100-penalty)));
  const status=score>=86?'ready for file':score>=64?'review queue':'compliance blocker';
  const action=status==='ready for file'?'Keep in load file and monitor expiry.':status==='review queue'?'Assign owner and verify before invoice/tender/payment step.':'Stop workflow until missing or blocked document is resolved by a human.';
  return {...d,score,status,blockers:blockers.length?blockers:['document clears local checks'],action};
}
function audits(){return state.docs.map(docAudit).sort((a,b)=>a.score-b.score||a.dueHours-b.dueHours);}
function vaultScore(){const list=audits(); return list.length?Math.round(list.reduce((s,d)=>s+d.score,0)/list.length):0;}
function missingQueue(){return audits().filter(d=>d.status!=='ready for file');}
function scorecards(){const list=audits(); const missing=list.filter(d=>d.status==='compliance blocker'); const review=list.filter(d=>d.status==='review queue'); const pod=list.filter(d=>d.docType==='POD'&&d.status!=='ready for file'); const coi=list.filter(d=>d.docType==='COI'&&d.status!=='ready for file'); return [
 {title:'Blocked documents',value:`${missing.length}`,tone:missing.length?'bad':'good',body:missing.length?`${missing.map(d=>d.id).join(', ')} block workflow steps.`:'No document is blocking the mock workflow.'},
 {title:'Review queue',value:`${review.length}`,tone:review.length?'warn':'good',body:review.length?`${review.map(d=>d.id).join(', ')} need owner review.`:'No review-only documents.'},
 {title:'POD cash risk',value:`${pod.length}`,tone:pod.length?'warn':'good',body:pod.length?'POD gaps can delay invoicing, factoring, and customer payment.':'POD queue is clear in demo data.'},
 {title:'Carrier compliance risk',value:`${coi.length}`,tone:coi.length?'warn':'good',body:coi.length?'COI/insurance gaps need compliance review before tender or payment reliance.':'COI checks clear local thresholds.'}
];}
function rowEditor(d,i){const fields=['id','loadId','carrier','customer','docType','status','required','dueHours','ageHours','expiresInDays','insuranceValue','owner','notes']; return `<article class="doc-card" data-i="${i}"><div class="doc-grid">${fields.map(k=>{const label={loadId:'load id',docType:'doc type',dueHours:'due hours',ageHours:'age hours',expiresInDays:'expires in days',insuranceValue:'insurance $'}[k]||k; if(k==='docType')return `<label>${label}<select data-k="docType">${['rate con','POD','BOL','COI','W9','carrier packet','invoice backup'].map(x=>`<option ${d.docType===x?'selected':''}>${x}</option>`).join('')}</select></label>`; if(k==='status')return `<label>${label}<select data-k="status">${['verified','missing','review','expiring'].map(x=>`<option ${d.status===x?'selected':''}>${x}</option>`).join('')}</select></label>`; if(k==='required')return `<label>${label}<select data-k="required"><option ${d.required==='yes'?'selected':''}>yes</option><option ${d.required==='no'?'selected':''}>no</option></select></label>`; const type=['dueHours','ageHours','expiresInDays','insuranceValue'].includes(k)?'number':'text'; return `<label class="${['notes','customer','carrier'].includes(k)?'wide':''}">${label}<input data-k="${k}" type="${type}" value="${escapeAttr(d[k])}"></label>`;}).join('')}</div><footer><span class="pill">${d.id}</span><button class="danger" data-remove="${i}">Remove</button></footer></article>`;}
function brief(){const list=audits(); const queue=missingQueue(); const cards=scorecards(); const lines=['# Document Compliance Vault brief','',`Generated: ${new Date().toLocaleString()}`,'Local mock/demo document-control output. Human broker/admin approval is required before relying on real documents, invoicing, tendering, dispatching, contacting carriers/customers, writing TMS/CRM/EDI, using credentials, or spending money.','',`Vault readiness: ${vaultScore()}%`,`Queue needing action: ${queue.length}/${list.length}`,'','## Missing/review queue']; queue.forEach((d,i)=>lines.push(`${i+1}. ${d.id} ${d.loadId} ${d.docType}: ${d.status}, score ${d.score}%, owner ${d.owner}, checks: ${d.blockers.join('; ')}. Action: ${d.action}`)); lines.push('', '## Scorecards'); cards.forEach(c=>lines.push(`- ${c.title}: ${c.value} — ${c.body}`)); lines.push('', '## Ready records'); list.filter(d=>d.status==='ready for file').forEach(d=>lines.push(`- ${d.id} ${d.loadId} ${d.docType}: ready for file.`)); lines.push('', '## Safety boundary','No real file reading/upload, scraping, carrier/customer/facility contact, posting, tendering, dispatching, billing, TMS/CRM/EDI writes, credential use, spend, or public/customer-facing action happens here.'); return lines.join('\n');}
function updateOutputs(){const list=audits(); const q=missingQueue(); const score=vaultScore(); $('vaultScore').textContent=pct(score); $('vaultLabel').textContent=`${q.length} queue item(s) · ${list.length} records`; $('brief').value=brief(); $('missingSummary').textContent=`${q.length} gaps/reviews`; $('missingRows').innerHTML=(q.length?q:list).map(d=>`<article class="result-card"><h3>${d.id} · ${d.docType}</h3><span class="pill ${d.status==='ready for file'?'good':d.status==='review queue'?'warn':'bad'}">${d.status}</span><strong>${pct(d.score)}</strong><p>${d.loadId} / ${d.carrier}</p><p>${d.blockers.join('; ')}</p><p>${d.action}</p></article>`).join(''); const cards=scorecards(); $('scoreSummary').textContent=`${cards.length} controls checked`; $('scoreRows').innerHTML=cards.map(c=>`<article class="result-card"><h3>${c.title}</h3><span class="pill ${c.tone}">${c.tone}</span><strong>${c.value}</strong><p>${c.body}</p></article>`).join(''); save();}
function render(){document.documentElement.dataset.theme=state.theme; $('themeToggle').textContent=state.theme==='light'?'Dark':'Light'; ['missingPenalty','expiringSoonDays','podChaseHours','coiMinInsurance','reviewStance'].forEach(k=>{$(k).value=state[k];}); $('docCount').textContent=`${state.docs.length} records`; $('docRows').innerHTML=state.docs.map(rowEditor).join(''); document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const card=el.closest('.doc-card'); state.docs[Number(card.dataset.i)][el.dataset.k]=el.value; save(); updateOutputs();})); document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{state.docs.splice(Number(btn.dataset.remove),1); save(); render(); toast('Document removed');})); updateOutputs();}
function toast(message){const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),1600);}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);}
function csv(){const header='rank,id,load_id,doc_type,status,score,owner,due_hours,age_hours,expires_in_days,insurance_value,blockers'; return [header,...audits().map((d,i)=>[i+1,d.id,d.loadId,d.docType,d.status,d.score,d.owner,d.dueHours,d.ageHours,d.expiresInDays,d.insuranceValue,d.blockers.join('; ')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))].join('\n');}
['missingPenalty','expiringSoonDays','podChaseHours','coiMinInsurance','reviewStance'].forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value; save(); updateOutputs();}));
$('loadDemo').onclick=()=>{state={...clone(DEFAULTS),theme:state.theme}; render(); toast('Demo vault loaded');};
$('addDoc').onclick=()=>{state.docs.push({id:`DOC-${Date.now().toString().slice(-4)}`,loadId:'BH-manual',carrier:'Manual carrier',customer:'Manual customer',docType:'POD',status:'missing',required:'yes',dueHours:12,ageHours:0,expiresInDays:365,insuranceValue:0,owner:'broker ops',notes:'Manual document record.'}); render(); toast('Document added');};
$('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light'; render();};
$('copyBrief').onclick=()=>navigator.clipboard?.writeText($('brief').value).then(()=>toast('Brief copied')).catch(()=>{$('brief').focus();$('brief').select();});
$('downloadJson').onclick=()=>download('document-compliance-vault.json',JSON.stringify({controls:{missingPenalty:state.missingPenalty,expiringSoonDays:state.expiringSoonDays,podChaseHours:state.podChaseHours,coiMinInsurance:state.coiMinInsurance,reviewStance:state.reviewStance},documents:state.docs,audits:audits(),missingQueue:missingQueue(),scorecards:scorecards(),brief:brief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('document-compliance-vault.csv',csv(),'text/csv');
$('downloadMarkdown').onclick=()=>download('document-compliance-vault.md',brief(),'text/markdown');
render();
