const STORAGE='tender-packet-builder-v1';
const DEMO={theme:'dark',approvalStance:'balanced',minMargin:15,minReadyCarriers:2,expiresHours:6,requireDocs:'yes',humanApproval:'required',load:{loadId:'TP-5001',customer:'Blue River Foods',origin:'Chicago, IL',destination:'Atlanta, GA',equipment:'Dry Van',commodity:'Packaged retail goods',weight:42000,miles:716,pickupWindow:'2026-07-14 08:00-12:00',deliveryWindow:'2026-07-15 09:00-14:00',sellPrice:2525,targetBuy:2075,readyCarriers:3,insuranceRequired:1.0,facilityNotes:'Driver must call check-in desk 30 minutes before arrival; seal photos required.',brokerCaveat:'Draft packet only; verify appointment, carrier packet, insurance, and customer approval before any tender.'},requirements:[{text:'Signed rate confirmation with pickup/delivery windows, commodity, weight, and accessorial terms.',priority:'required'},{text:'Carrier packet, W9, COI, authority, safety, tracking, and fraud review complete before dispatch.',priority:'required'},{text:'Driver arrival call plus macro/check-call cadence documented for dispatch handoff.',priority:'important'}],caveats:[{text:'Do not tender until human broker approves price, carrier, appointment, and customer caveats.',severity:'blocker'},{text:'Confirm detention, layover, lumper, TONU, and after-hours terms before customer send.',severity:'review'},{text:'No live systems are updated from this local draft packet.',severity:'notice'}]};
const DEFAULTS=DEMO;
const $=id=>document.getElementById(id); const num=v=>Number(v)||0; const money=n=>'$'+Math.round(num(n)).toLocaleString(); const pct=n=>`${Math.round(num(n))}%`; const clone=v=>JSON.parse(JSON.stringify(v));
let state=loadState();
function loadState(){try{return {...clone(DEFAULTS),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function margin(){return num(state.load.sellPrice)?(num(state.load.sellPrice)-num(state.load.targetBuy))/num(state.load.sellPrice)*100:0;}
function readinessAudit(){
  const l=state.load; const checks=[
    {title:'Required lane facts',pass:!!(l.loadId&&l.customer&&l.origin&&l.destination&&l.equipment&&l.commodity&&num(l.weight)>0&&num(l.miles)>0),detail:'Load id, customer, origin, destination, equipment, commodity, weight, and miles are filled.'},
    {title:'Appointment windows',pass:!!(l.pickupWindow&&l.deliveryWindow),detail:'Pickup and delivery windows are present for rate confirmation and dispatch.'},
    {title:'Margin guardrail',pass:margin()>=num(state.minMargin),detail:`Margin ${pct(margin())} vs minimum ${state.minMargin}%.`},
    {title:'Carrier availability',pass:num(l.readyCarriers)>=num(state.minReadyCarriers),detail:`${l.readyCarriers} ready carrier(s) vs minimum ${state.minReadyCarriers}.`},
    {title:'Requirements captured',pass:state.requirements.filter(r=>r.priority==='required').length>=2,detail:'Required operating requirements are listed.'},
    {title:'Caveat / blocker gate',pass:state.caveats.some(c=>c.severity==='blocker'),detail:'At least one explicit no-send blocker is captured.'},
    {title:'Documents policy',pass:state.requireDocs==='no'||state.requirements.some(r=>/coi|rate confirmation|carrier packet|w9|authority/i.test(r.text)),detail:'Required documentation terms are represented.'},
    {title:'Human approval',pass:state.humanApproval==='required',detail:'Human approval is required before any operational action.'}
  ];
  const score=Math.round(checks.filter(c=>c.pass).length/checks.length*100);
  return {checks,score,status:score>=88?'ready':score>=65?'review':'blocked'};
}
function approvalGates(){const audit=readinessAudit(); const strict=state.approvalStance==='strict'; return [
  {title:'Send/tender lock',tone:state.humanApproval==='required'?'good':'bad',body:state.humanApproval==='required'?'Packet cannot be used operationally until a human approves.':'Set human approval to required before using packet text.'},
  {title:'Rate floor',tone:margin()>=num(state.minMargin)+(strict?2:0)?'good':'warn',body:`Sell ${money(state.load.sellPrice)}, target buy ${money(state.load.targetBuy)}, margin ${pct(margin())}.`},
  {title:'Capacity gate',tone:num(state.load.readyCarriers)>=num(state.minReadyCarriers)?'good':'warn',body:`${state.load.readyCarriers} ready carrier(s) documented before tender packet handoff.`},
  {title:'Packet expiry',tone:num(state.expiresHours)<=8?'good':'warn',body:`Draft packet expires in ${state.expiresHours} hour(s) so stale rates do not leak into operations.`},
  {title:'Readiness verdict',tone:audit.status==='ready'?'good':audit.status==='review'?'warn':'bad',body:`Overall readiness is ${audit.score}% (${audit.status}).`}
];}
function itemEditor(kind,item,i){const priority=kind==='requirements'?['required','important','optional']:['blocker','review','notice']; return `<article class="item-card" data-kind="${kind}" data-i="${i}"><div class="item-grid"><label>${kind==='requirements'?'requirement':'caveat'}<input data-k="text" value="${String(item.text||'').replace(/"/g,'&quot;')}"></label><label>level<select data-k="${kind==='requirements'?'priority':'severity'}">${priority.map(p=>`<option ${item.priority===p||item.severity===p?'selected':''}>${p}</option>`).join('')}</select></label></div><footer><span class="pill">${item.priority||item.severity}</span><button class="danger" data-remove="${kind}:${i}">Remove</button></footer></article>`;}
function packetMarkdown(){const l=state.load; const audit=readinessAudit(); const lines=['# Tender Packet Builder draft','',`Generated: ${new Date().toLocaleString()}`,'Local mock/demo draft only. Human broker approval is required before any customer/carrier send, tender, posting, TMS/CRM/EDI write, external credential use, spend, or operational commitment.','',`Readiness: ${audit.score}% (${audit.status})`,`Expires: ${state.expiresHours} hour(s) after generation`,`Approval stance: ${state.approvalStance}`,'','## Load facts',`- Load ID: ${l.loadId}`,`- Customer: ${l.customer}`,`- Lane: ${l.origin} -> ${l.destination}`,`- Equipment / commodity / weight: ${l.equipment} / ${l.commodity} / ${Number(l.weight).toLocaleString()} lbs`,`- Miles: ${l.miles}`,`- Pickup: ${l.pickupWindow}`,`- Delivery: ${l.deliveryWindow}`,`- Sell price: ${money(l.sellPrice)}`,`- Target buy: ${money(l.targetBuy)}`,`- Draft margin: ${pct(margin())}`,`- Ready carriers: ${l.readyCarriers}`,`- Insurance required: $${Number(l.insuranceRequired||0).toFixed(1)}M`,'','## Requirements']; state.requirements.forEach((r,i)=>lines.push(`${i+1}. [${r.priority}] ${r.text}`)); lines.push('','## Caveats and approval gates'); state.caveats.forEach((c,i)=>lines.push(`${i+1}. [${c.severity}] ${c.text}`)); lines.push('', '## Facility / broker notes', `- Facility: ${l.facilityNotes}`, `- Broker caveat: ${l.brokerCaveat}`,'','## Approval gate audit'); approvalGates().forEach(g=>lines.push(`- ${g.title}: ${g.tone.toUpperCase()} — ${g.body}`)); lines.push('', '## Packet assembly checklist'); audit.checks.forEach(c=>lines.push(`- ${c.pass?'PASS':'REVIEW'} — ${c.title}: ${c.detail}`)); lines.push('', '## Monetization angle','Tender Packet Builder packages the broker handoff layer for Backhaul: consistent tender drafts, no-send gates, margin/capacity checks, and exportable packet text before any operational system is touched.', '', '## Safety boundary','This static local prototype never sends, posts, contacts, scrapes, writes to systems, calls external APIs, uses credentials, spends money, or approves freight movement.'); return lines.join('\n');}
function render(){document.documentElement.dataset.theme=state.theme; $('themeToggle').textContent=state.theme==='light'?'Dark':'Light'; ['approvalStance','minMargin','minReadyCarriers','expiresHours','requireDocs','humanApproval'].forEach(k=>{$(k).value=state[k];}); Object.keys(state.load).forEach(k=>{if($(k))$(k).value=state.load[k];}); $('loadIdLabel').textContent=state.load.loadId||'No load id'; $('requirementCount').textContent=`${state.requirements.length}`; $('caveatCount').textContent=`${state.caveats.length}`; $('requirementRows').innerHTML=state.requirements.map((r,i)=>itemEditor('requirements',r,i)).join(''); $('caveatRows').innerHTML=state.caveats.map((c,i)=>itemEditor('caveats',c,i)).join(''); document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const card=el.closest('.item-card'); const collection=card.dataset.kind; state[collection][Number(card.dataset.i)][el.dataset.k]=el.value; save(); updateOutputs();})); document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{const [kind,i]=btn.dataset.remove.split(':'); state[kind].splice(Number(i),1); save(); render(); toast('Item removed');})); updateOutputs(); save();}
function updateOutputs(){const audit=readinessAudit(); $('readinessScore').textContent=pct(audit.score); $('readinessLabel').textContent=`${audit.status} · margin ${pct(margin())}`; $('packet').value=packetMarkdown(); $('gateSummary').textContent=`${approvalGates().length} gates`; $('gateRows').innerHTML=approvalGates().map(g=>`<article class="audit-card"><h3>${g.title}</h3><span class="pill ${g.tone}">${g.tone}</span><p>${g.body}</p></article>`).join(''); $('checkSummary').textContent=`${audit.checks.filter(c=>c.pass).length}/${audit.checks.length} pass`; $('checkRows').innerHTML=audit.checks.map(c=>`<article class="audit-card"><h3>${c.title}</h3><span class="pill ${c.pass?'good':'warn'}">${c.pass?'pass':'review'}</span><p>${c.detail}</p></article>`).join(''); save();}
function toast(message){const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),1600);}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);}
['approvalStance','minMargin','minReadyCarriers','expiresHours','requireDocs','humanApproval'].forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value; save(); updateOutputs();}));
Object.keys(state.load).forEach(k=>{if($(k))$(k).addEventListener('input',()=>{state.load[k]=$(k).value; save(); updateOutputs();});});
$('loadDemo').onclick=()=>{state={...clone(DEFAULTS),theme:state.theme}; render(); toast('Demo packet loaded');};
$('addRequirement').onclick=()=>{state.requirements.push({text:'New tender requirement for broker review.',priority:'important'}); render(); toast('Requirement added');};
$('addCaveat').onclick=()=>{state.caveats.push({text:'New caveat requiring human review before send.',severity:'review'}); render(); toast('Caveat added');};
$('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light'; render();};
$('copyPacket').onclick=()=>navigator.clipboard?.writeText($('packet').value).then(()=>toast('Packet copied')).catch(()=>{$('packet').focus();$('packet').select();});
$('downloadJson').onclick=()=>download('tender-packet-builder.json',JSON.stringify({controls:{approvalStance:state.approvalStance,minMargin:state.minMargin,minReadyCarriers:state.minReadyCarriers,expiresHours:state.expiresHours,requireDocs:state.requireDocs,humanApproval:state.humanApproval},load:state.load,requirements:state.requirements,caveats:state.caveats,readinessAudit:readinessAudit(),approvalGates:approvalGates(),packet:packetMarkdown(),safety:'local draft only'},null,2),'application/json');
$('downloadMarkdown').onclick=()=>download('tender-packet-builder.md',packetMarkdown(),'text/markdown');
/* Hour 06 cumulative enhancement: post-tender lifecycle checklist. */
function postTenderLifecycleChecklist(){
  const l=state.load; const stages=[
    {stage:'covered',title:'Coverage locked',pass:num(l.readyCarriers)>=num(state.minReadyCarriers)&&readinessAudit().score>=75,detail:`${l.readyCarriers} ready carrier(s), readiness ${readinessAudit().score}%.`},
    {stage:'dispatched',title:'Dispatch facts ready',pass:!!(l.pickupWindow&&l.deliveryWindow&&l.facilityNotes),detail:'Pickup/delivery windows and facility notes must be handed to dispatch.'},
    {stage:'picked',title:'Pickup proof',pass:state.requirements.some(r=>/check|arrival|driver|seal/i.test(r.text)),detail:'Driver arrival/check-call/seal proof requirement should be present.'},
    {stage:'delivered',title:'Delivery caveats',pass:state.caveats.some(c=>/detention|layover|lumper|after-hours|delivery/i.test(c.text)),detail:'Delivery/accessorial caveats should be captured before dispatch.'},
    {stage:'pod',title:'POD requirement',pass:state.requirements.some(r=>/pod|bol|delivery/i.test(r.text)),detail:'POD/BOL document requirement must be explicit.'},
    {stage:'invoice',title:'Invoice packet',pass:state.requireDocs==='yes',detail:'Rate confirmation, BOL/POD, and invoice packet policy is required.'},
    {stage:'paid',title:'Cash closeout',pass:margin()>=num(state.minMargin),detail:`Margin ${pct(margin())} should clear the cash closeout floor.`}
  ];
  return state.postTenderFocus&&state.postTenderFocus!=='all'?stages.filter(s=>s.stage===state.postTenderFocus):stages;
}
const __h6TenderBasePacket=packetMarkdown;
packetMarkdown=function(){const base=__h6TenderBasePacket(); const checks=postTenderLifecycleChecklist(); return base.replace('\n## Monetization angle', `\n## Post-tender lifecycle checklist\n${checks.map((c,i)=>`${i+1}. ${c.stage}: ${c.pass?'PASS':'REVIEW'} — ${c.title}. ${c.detail}`).join('\n')}\n\n## Monetization angle`);};
const __h6TenderBaseUpdate=updateOutputs;
updateOutputs=function(){__h6TenderBaseUpdate(); const checks=postTenderLifecycleChecklist(); const review=checks.filter(c=>!c.pass); if($('postTenderSummary'))$('postTenderSummary').textContent=`${checks.length-review.length}/${checks.length} stage checks pass`; if($('postTenderRows'))$('postTenderRows').innerHTML=checks.map(c=>`<article class="audit-card"><h3>${c.stage} · ${c.title}</h3><span class="pill ${c.pass?'good':'warn'}">${c.pass?'pass':'review'}</span><p>${c.detail}</p></article>`).join(''); if($('packet'))$('packet').value=packetMarkdown(); save();};
const __h6TenderBaseRender=render;
render=function(){__h6TenderBaseRender(); if(state.postTenderFocus===undefined)state.postTenderFocus='all'; const ctl=$('postTenderFocus'); if(ctl)ctl.value=state.postTenderFocus;};
if(state.postTenderFocus===undefined)state.postTenderFocus='all';
const __h6PostTenderCtl=$('postTenderFocus'); if(__h6PostTenderCtl)__h6PostTenderCtl.addEventListener('input',()=>{state.postTenderFocus=__h6PostTenderCtl.value;save();updateOutputs();});
$('downloadJson').onclick=()=>download('tender-packet-builder.json',JSON.stringify({controls:{approvalStance:state.approvalStance,minMargin:state.minMargin,minReadyCarriers:state.minReadyCarriers,expiresHours:state.expiresHours,requireDocs:state.requireDocs,humanApproval:state.humanApproval,postTenderFocus:state.postTenderFocus},load:state.load,requirements:state.requirements,caveats:state.caveats,readinessAudit:readinessAudit(),approvalGates:approvalGates(),postTenderLifecycleChecklist:postTenderLifecycleChecklist(),packet:packetMarkdown(),safety:'local draft only'},null,2),'application/json');
/* Hour 07 cumulative enhancement: detention clause checklist. */
function detentionClauseChecklist(){
  const text=[...state.requirements.map(r=>r.text),...state.caveats.map(c=>c.text),state.load.facilityNotes,state.load.specialInstructions].join(' ').toLowerCase();
  const strict=state.detentionClauseStrictness==='strict';
  const checks=[
    {key:'free-time',title:'Free-time term',pass:/free|detention|dwell/.test(text),detail:'Tender should state free time / detention clock trigger.'},
    {key:'timestamps',title:'Signed in/out timestamps',pass:/time|timestamp|in\/out|check.?in|check.?out|arrival/.test(text),detail:'Driver/carrier must capture signed arrival and release times.'},
    {key:'approval',title:'Approval path',pass:/approval|authorize|broker review|human review/.test(text),detail:'Accessorial request must remain human-approved before billing.'},
    {key:'docs',title:'Document proof',pass:/pod|bol|receipt|lumper|document/.test(text),detail:'Detention needs POD/BOL/lumper/notes proof before invoice.'},
    {key:'appointment',title:'Appointment protection',pass:/appointment|window|facility/.test(text),detail:'Pickup/delivery window and facility notes must be explicit.'}
  ];
  return strict?checks:checks.filter(c=>state.detentionClauseStrictness==='light'?['free-time','timestamps','approval'].includes(c.key):true);
}
const __h7TenderBasePacket=packetMarkdown;
packetMarkdown=function(){const base=__h7TenderBasePacket(); const checks=detentionClauseChecklist(); return base.replace('\n## Monetization angle', `\n## Detention clause checklist\n${checks.map((c,i)=>`${i+1}. ${c.pass?'PASS':'REVIEW'} — ${c.title}. ${c.detail}`).join('\n')}\n\n## Monetization angle`);};
const __h7TenderBaseUpdate=updateOutputs;
updateOutputs=function(){__h7TenderBaseUpdate(); const checks=detentionClauseChecklist(); const review=checks.filter(c=>!c.pass); if($('detentionClauseSummary'))$('detentionClauseSummary').textContent=`${checks.length-review.length}/${checks.length} detention checks pass`; if($('detentionClauseRows'))$('detentionClauseRows').innerHTML=checks.map(c=>`<article class="audit-card"><h3>${c.title}</h3><span class="pill ${c.pass?'good':'warn'}">${c.pass?'pass':'review'}</span><p>${c.detail}</p></article>`).join(''); if($('packet'))$('packet').value=packetMarkdown(); save();};
const __h7TenderBaseRender=render;
render=function(){__h7TenderBaseRender(); if(state.detentionClauseStrictness===undefined)state.detentionClauseStrictness='balanced'; const ctl=$('detentionClauseStrictness'); if(ctl)ctl.value=state.detentionClauseStrictness;};
if(state.detentionClauseStrictness===undefined)state.detentionClauseStrictness='balanced';
const __h7ClauseCtl=$('detentionClauseStrictness'); if(__h7ClauseCtl)__h7ClauseCtl.addEventListener('input',()=>{state.detentionClauseStrictness=__h7ClauseCtl.value;save();updateOutputs();});
$('downloadJson').onclick=()=>download('tender-packet-builder.json',JSON.stringify({controls:{...state},load:state.load,requirements:state.requirements,caveats:state.caveats,readinessAudit:readinessAudit(),approvalGates:approvalGates(),postTenderLifecycleChecklist:postTenderLifecycleChecklist(),detentionClauseChecklist:detentionClauseChecklist(),packet:packetMarkdown(),safety:'local draft only'},null,2),'application/json');
/* Hour 08 cumulative enhancement: appointment confirmation checklist. */
function appointmentConfirmationChecklist(){const l=state.load; const text=[l.pickupWindow,l.deliveryWindow,l.facilityNotes,l.brokerCaveat,...state.requirements.map(r=>r.text),...state.caveats.map(c=>c.text)].join(' ').toLowerCase(); return [
  {title:'Pickup window captured',pass:!!l.pickupWindow,detail:'Pickup date/time window must be explicit before tender.'},
  {title:'Delivery window captured',pass:!!l.deliveryWindow,detail:'Delivery appointment/request must be explicit before tender.'},
  {title:'Facility appointment notes',pass:/appointment|check-in|arrival|facility|desk|call/i.test(text),detail:'Facility check-in/arrival instructions should be documented.'},
  {title:'Carrier confirmation path',pass:/carrier|driver|dispatch|check-call|tracking/i.test(text),detail:'Carrier/driver confirmation and check-call path should be listed.'},
  {title:'Human approval hold',pass:state.humanApproval==='required',detail:'Human broker approval remains required before appointment/tender action.'}
];}
const __h8TenderBasePacket=packetMarkdown;
packetMarkdown=function(){const base=__h8TenderBasePacket(); const checks=appointmentConfirmationChecklist(); return base.replace('\n## Monetization angle', `\n## Appointment confirmation checklist\n${checks.map((c,i)=>`${i+1}. ${c.pass?'PASS':'REVIEW'} — ${c.title}. ${c.detail}`).join('\n')}\n\n## Monetization angle`);};
const __h8TenderBaseUpdate=updateOutputs;
updateOutputs=function(){__h8TenderBaseUpdate(); const checks=appointmentConfirmationChecklist(); const review=checks.filter(c=>!c.pass); if($('appointmentChecklistSummary'))$('appointmentChecklistSummary').textContent=`${checks.length-review.length}/${checks.length} appointment checks pass`; if($('appointmentChecklistRows'))$('appointmentChecklistRows').innerHTML=checks.map(c=>`<article class="audit-card"><h3>${c.title}</h3><span class="pill ${c.pass?'good':'warn'}">${c.pass?'pass':'review'}</span><p>${c.detail}</p></article>`).join(''); if($('packet'))$('packet').value=packetMarkdown(); save();};
$('downloadJson').onclick=()=>download('tender-packet-builder.json',JSON.stringify({controls:{...state},load:state.load,requirements:state.requirements,caveats:state.caveats,readinessAudit:readinessAudit(),approvalGates:approvalGates(),postTenderLifecycleChecklist:postTenderLifecycleChecklist(),detentionClauseChecklist:detentionClauseChecklist(),appointmentConfirmationChecklist:appointmentConfirmationChecklist(),packet:packetMarkdown(),safety:'local draft only'},null,2),'application/json');

/* Hour 09 cumulative enhancement: document attachment manifest. */
function documentAttachmentManifest(){const l=state.load; const text=[l.loadId,l.customer,l.carrier,l.facilityNotes,l.brokerCaveat,...state.requirements.map(r=>r.text),...state.caveats.map(c=>c.text)].join(' ').toLowerCase(); return [
  {title:'Rate confirmation facts',pass:!!l.loadId&&!!l.sell&&!!l.buy,detail:'Load ID plus buy/sell economics must be in the packet.'},
  {title:'BOL/POD expectation',pass:/bol|pod|proof|signed|delivery/i.test(text),detail:'Packet should state BOL/POD proof expectations.'},
  {title:'Carrier packet/COI reference',pass:/coi|insurance|w9|carrier packet|authority/i.test(text),detail:'Carrier compliance docs should be referenced before tender reliance.'},
  {title:'Accessorial proof path',pass:/detention|accessorial|timestamp|in\/out|approval/i.test(text),detail:'Accessorials need proof and approval language.'},
  {title:'Human document review',pass:state.humanApproval==='required'&&state.requireDocs==='yes',detail:'Human review and required docs stay enabled.'}
];}
const __h9TenderBasePacket=packetMarkdown;
packetMarkdown=function(){const base=__h9TenderBasePacket(); const checks=documentAttachmentManifest(); return base.replace('\n## Monetization angle', `\n## Document attachment manifest\n${checks.map((c,i)=>`${i+1}. ${c.pass?'PASS':'REVIEW'} — ${c.title}. ${c.detail}`).join('\n')}\n\n## Monetization angle`);};
const __h9TenderBaseUpdate=updateOutputs;
updateOutputs=function(){__h9TenderBaseUpdate(); const checks=documentAttachmentManifest(); const review=checks.filter(c=>!c.pass); if($('docManifestSummary'))$('docManifestSummary').textContent=`${checks.length-review.length}/${checks.length} document checks pass`; if($('docManifestRows'))$('docManifestRows').innerHTML=checks.map(c=>`<article class="audit-card"><h3>${c.title}</h3><span class="pill ${c.pass?'good':'warn'}">${c.pass?'pass':'review'}</span><p>${c.detail}</p></article>`).join(''); if($('packet'))$('packet').value=packetMarkdown(); save();};
$('downloadJson').onclick=()=>download('tender-packet-builder.json',JSON.stringify({controls:{...state},load:state.load,requirements:state.requirements,caveats:state.caveats,readinessAudit:readinessAudit(),approvalGates:approvalGates(),postTenderLifecycleChecklist:postTenderLifecycleChecklist(),detentionClauseChecklist:detentionClauseChecklist(),appointmentConfirmationChecklist:appointmentConfirmationChecklist(),documentAttachmentManifest:documentAttachmentManifest(),packet:packetMarkdown(),safety:'local draft only'},null,2),'application/json');

render();
