const STORAGE='loadboard-signal-console-v2';
const demo=[
{id:'L-1001',origin:'Chicago, IL',destination:'Atlanta, GA',equipment:'Dry Van',miles:716,deadhead:58,sell:2450,buy:2025,age:42,risk:'low',notes:'Good southeast backhaul, macro tracking carrier fit.'},
{id:'L-1002',origin:'Columbus, OH',destination:'Dallas, TX',equipment:'Reefer',miles:1064,deadhead:142,sell:3920,buy:3375,age:95,risk:'medium',notes:'Longer deadhead but strong gross dollars.'},
{id:'L-1003',origin:'Memphis, TN',destination:'Indianapolis, IN',equipment:'Flatbed',miles:463,deadhead:38,sell:1780,buy:1515,age:18,risk:'low',notes:'Short reload loop, appointment risk low.'},
{id:'L-1004',origin:'Savannah, GA',destination:'Louisville, KY',equipment:'Dry Van',miles:612,deadhead:210,sell:2250,buy:1990,age:124,risk:'high',notes:'Deadhead and posting age weaken fit; review manually.'}
];
const DEFAULTS={theme:'dark',loads:demo,targetOrigin:'Midwest',targetDestination:'Southeast',minMargin:14,maxDeadhead:125,riskTolerance:'balanced',floorRpm:2.2,targetMargin:17,floorSeverity:'balanced',laneShareLimit:40};
const $=id=>document.getElementById(id); const money=n=>'$'+Math.round(Number(n)||0).toLocaleString(); const pct=n=>`${Math.round(Number(n)||0)}%`; const num=v=>Number(v)||0; const clone=v=>JSON.parse(JSON.stringify(v));
let state=load();
function load(){try{return {...clone(DEFAULTS),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function calc(l){const gross=num(l.sell)-num(l.buy);const margin=num(l.sell)?gross/num(l.sell)*100:0;const rpm=num(l.sell)/Math.max(num(l.miles),1);const floorSellByRpm=num(state.floorRpm)*num(l.miles);const floorSellByMargin=num(l.buy)/(1-(num(state.targetMargin)/100||0.01));const suggestedSell=Math.ceil(Math.max(floorSellByRpm,floorSellByMargin)/25)*25;const askGap=Math.max(0,suggestedSell-num(l.sell));const gapPct=num(l.sell)?askGap/num(l.sell)*100:0;let score=50+Math.min(28,margin*1.4)+Math.max(-20,20-num(l.deadhead)/7)-Math.min(18,num(l.age)/9); if(l.risk==='high')score-=18; if(l.risk==='medium')score-=7; if(num(l.deadhead)>num(state.maxDeadhead))score-=8; if(margin<num(state.minMargin))score-=8; const severity=state.floorSeverity==='strict'?1.15:state.floorSeverity==='opportunistic'?0.8:1; score-=Math.min(15,gapPct*severity); return {gross,margin,rpm,floorSellByRpm,floorSellByMargin,suggestedSell,askGap,gapPct,belowFloor:askGap>0,score:Math.max(0,Math.min(99,Math.round(score)))} }
function render(){document.documentElement.dataset.theme=state.theme;$('themeToggle').textContent=state.theme==='light'?'Dark':'Light';['targetOrigin','targetDestination','minMargin','maxDeadhead','riskTolerance','floorRpm','targetMargin','floorSeverity','laneShareLimit'].forEach(k=>{$(k).value=state[k]});$('rowCount').textContent=`${state.loads.length} rows`; $('loadRows').innerHTML=state.loads.map((l,i)=>{const c=calc(l); const klass=c.score>72?'good':c.score>52?'warn':'bad'; return `<article class="row" data-i="${i}"><div class="row-grid">${['id','origin','destination','equipment','miles','deadhead','sell','buy','age'].map(k=>`<label>${k}<input data-k="${k}" value="${l[k]??''}" ${['miles','deadhead','sell','buy','age'].includes(k)?'type="number"':''}></label>`).join('')}<label>risk<select data-k="risk"><option ${l.risk==='low'?'selected':''}>low</option><option ${l.risk==='medium'?'selected':''}>medium</option><option ${l.risk==='high'?'selected':''}>high</option></select></label></div><label>notes<input data-k="notes" value="${String(l.notes||'').replace(/"/g,'&quot;')}"></label><div class="row-score"><span class="pill ${klass}">fit ${c.score}</span><span class="pill">gross ${money(c.gross)}</span><span class="pill">margin ${pct(c.margin)}</span><span class="pill">sell RPM $${c.rpm.toFixed(2)}</span><span class="pill ${c.belowFloor?'warn':'good'}">ask gap ${money(c.askGap)}</span><button class="secondary" data-remove="${i}">Remove</button></div></article>`}).join(''); document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const row=el.closest('.row'); state.loads[row.dataset.i][el.dataset.k]=el.value; save(); updateOutputs()})); document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.loads.splice(+b.dataset.remove,1);save();render();toast('Load removed')})); updateOutputs();}
function ranked(){return [...state.loads].map(l=>({...l,...calc(l)})).sort((a,b)=>b.score-a.score)}
function floorAudit(){return ranked().map(l=>({id:l.id,route:`${l.origin} -> ${l.destination}`,currentSell:num(l.sell),suggestedSell:l.suggestedSell,askGap:l.askGap,gapPct:l.gapPct,rpm:l.rpm,margin:l.margin,belowFloor:l.belowFloor,reason:l.belowFloor?`Needs ${money(l.askGap)} more to clear ${money(l.suggestedSell)} target ask.`:'Clears current ask floor.'})).sort((a,b)=>b.askGap-a.askGap)}
function exposureAudit(){const rows=ranked();const total=rows.reduce((s,l)=>s+num(l.sell),0)||1;const byLane={};rows.forEach(l=>{const lane=`${String(l.origin).split(',').pop()?.trim()||l.origin} -> ${String(l.destination).split(',').pop()?.trim()||l.destination}`;byLane[lane]=byLane[lane]||{lane,count:0,sell:0,gross:0,ids:[]};byLane[lane].count+=1;byLane[lane].sell+=num(l.sell);byLane[lane].gross+=num(l.gross);byLane[lane].ids.push(l.id)});return Object.values(byLane).map(x=>({...x,share:x.sell/total*100,over:x.sell/total*100>num(state.laneShareLimit)})).sort((a,b)=>b.share-a.share)}
function brief(){const list=ranked(); const audit=floorAudit(); const exposure=exposureAudit(); const value=list.reduce((s,l)=>s+(l.score>=55?l.gross:0),0); const gaps=audit.filter(a=>a.belowFloor); const exposed=exposure.filter(e=>e.over); return ['# Loadboard Signal Console brief','',`Generated: ${new Date().toLocaleString()}`,'Draft-only local brokerage signal. Human review required before quoting, posting, tendering, calling carriers, writing TMS/CRM, or spending money.','',`Board value in viable rows: ${money(value)}`,`Ask-floor guardrail: ${gaps.length} rows below target; total suggested ask lift ${money(gaps.reduce((s,g)=>s+g.askGap,0))}.`,`Lane concentration check: ${exposed.length} lane bucket(s) above ${state.laneShareLimit}% sell exposure.`,'', '## Top loads', ...list.map((l,i)=>`${i+1}. ${l.id} ${l.origin} -> ${l.destination} ${l.equipment}: fit ${l.score}, gross ${money(l.gross)}, margin ${pct(l.margin)}, deadhead ${l.deadhead} mi, age ${l.age} min, risk ${l.risk}, suggested ask ${money(l.suggestedSell)}${l.askGap?` (${money(l.askGap)} lift)`:''}. Notes: ${l.notes}`), '', '## Ask-floor audit', ...audit.map((a,i)=>`${i+1}. ${a.id}: current ${money(a.currentSell)}, suggested ${money(a.suggestedSell)}, gap ${money(a.askGap)}. ${a.reason}`), '', '## Lane concentration audit', ...exposure.map((e,i)=>`${i+1}. ${e.lane}: ${pct(e.share)} of board sell value across ${e.count} row(s), gross ${money(e.gross)}${e.over?' — diversify / price with concentration caution.':' — inside limit.'}`), '', '## Monetization angle','Package this as the first paid Backhaul module: aggregated loadboard scoring, backhaul-fit ranking, margin leakage visibility, ask-floor guardrails, lane concentration review, and broker action briefs for small brokerages or owner/operators.', '', '## Safety boundary','No live scraping, carrier contact, TMS writes, CRM writes, EDI/API calls, public posting, spend, or customer-facing commitments happen here.'].join('\n')}
function updateOutputs(){const list=ranked(); const audit=floorAudit(); const exposure=exposureAudit(); const value=list.reduce((s,l)=>s+(l.score>=55?l.gross:0),0); const gaps=audit.filter(a=>a.belowFloor); const exposed=exposure.filter(e=>e.over); $('boardValue').textContent=money(value); $('boardLabel').textContent=list[0]?`Best signal: ${list[0].id} / fit ${list[0].score}`:'Waiting for rows'; $('brief').value=brief(); $('floorSummary').textContent=`${gaps.length} review items · ${money(gaps.reduce((s,g)=>s+g.askGap,0))} ask lift`; $('floorRows').innerHTML=audit.map(a=>`<article class="floor-card"><h3>${a.id}</h3><p>${a.route}</p><strong>${a.askGap?money(a.askGap):'Clear'}</strong><p>Current ${money(a.currentSell)} · target ${money(a.suggestedSell)}</p><span class="pill ${a.belowFloor?'warn':'good'}">${a.belowFloor?'reprice before quote':'floor cleared'}</span></article>`).join(''); $('exposureSummary').textContent=`${exposed.length} over limit · ${exposure.length} buckets`; $('exposureRows').innerHTML=exposure.map(e=>`<article class="floor-card"><h3>${e.lane}</h3><p>${e.ids.join(', ')}</p><strong>${pct(e.share)}</strong><p>Sell ${money(e.sell)} · gross ${money(e.gross)}</p><span class="pill ${e.over?'warn':'good'}">${e.over?'concentration caution':'inside limit'}</span></article>`).join(''); save()}
function toast(m){const e=$('toast'); e.textContent=m; e.classList.add('show'); clearTimeout(window.__t); window.__t=setTimeout(()=>e.classList.remove('show'),1500)}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url)}
['targetOrigin','targetDestination','minMargin','maxDeadhead','riskTolerance','floorRpm','targetMargin','floorSeverity','laneShareLimit'].forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value;save();updateOutputs()}));
$('loadDemo').onclick=()=>{const theme=state.theme;state=clone(DEFAULTS);state.theme=theme; render(); toast('Demo board loaded')}; $('addLoad').onclick=()=>{state.loads.push({id:`L-${Date.now().toString().slice(-4)}`,origin:'New origin',destination:'New destination',equipment:'Dry Van',miles:500,deadhead:75,sell:2100,buy:1800,age:25,risk:'medium',notes:'Manual row'}); render()}; $('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light'; render()}; $('copyBrief').onclick=()=>navigator.clipboard?.writeText($('brief').value).then(()=>toast('Brief copied')).catch(()=>{$('brief').focus();$('brief').select()}); $('downloadJson').onclick=()=>download('loadboard-signal-console.json',JSON.stringify({settings:{targetOrigin:state.targetOrigin,targetDestination:state.targetDestination,minMargin:state.minMargin,maxDeadhead:state.maxDeadhead,riskTolerance:state.riskTolerance,floorRpm:state.floorRpm,targetMargin:state.targetMargin,floorSeverity:state.floorSeverity,laneShareLimit:state.laneShareLimit},loads:state.loads,ranked:ranked(),floorAudit:floorAudit(),exposureAudit:exposureAudit(),brief:brief(),safety:'local draft only'},null,2),'application/json'); $('downloadCsv').onclick=()=>download('loadboard-signal-console.csv',['id,origin,destination,equipment,miles,deadhead,sell,buy,gross,margin,score,risk,suggested_sell,ask_gap,lane_bucket_share',...ranked().map(l=>{const bucket=exposureAudit().find(e=>e.ids.includes(l.id));return [l.id,l.origin,l.destination,l.equipment,l.miles,l.deadhead,l.sell,l.buy,l.gross,l.margin.toFixed(1),l.score,l.risk,l.suggestedSell,l.askGap,bucket?bucket.share.toFixed(1):0].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')})].join('\n'),'text/csv');

/* Hour 04 cumulative enhancement: carrier readiness check for each loadboard row. */
function carrierReadyAudit(){
  const pools={'Dry Van':{vetted:7,tracking:91},'Reefer':{vetted:4,tracking:87},'Flatbed':{vetted:3,tracking:79},'Power Only':{vetted:2,tracking:73}};
  const min=num(state.carrierReadyMin||3);
  return ranked().map(l=>{const pool=pools[l.equipment]||{vetted:2,tracking:70}; let ready=pool.vetted; if(l.risk==='high')ready-=2; if(l.risk==='medium')ready-=1; if(num(l.deadhead)>num(state.maxDeadhead))ready-=1; if(num(l.age)>90)ready-=1; if(num(l.askGap)>0)ready-=1; ready=Math.max(0,ready); const score=Math.max(0,Math.min(99,Math.round(l.score+Math.min(12,ready*4)-Math.max(0,min-ready)*12))); const status=ready>=min&&score>=60?'ready':ready>0?'thin':'blocked'; return {...l,readyCarriers:ready,trackingConfidence:pool.tracking,carrierStatus:status,carrierScore:score,carrierReason:status==='ready'?'Enough vetted mock carriers clear lane/equipment risk.':status==='thin'?'Thin carrier pool; broker should widen vetted backup coverage before quoting.':'No vetted mock carrier pool clears this lane risk.'};}).sort((a,b)=>a.readyCarriers-b.readyCarriers||b.askGap-a.askGap);
}
const __h4LoadboardBaseBrief=brief;
brief=function(){const base=__h4LoadboardBaseBrief(); const audit=carrierReadyAudit(); return base.replace('\n## Monetization angle', `\n## Carrier readiness audit\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.carrierStatus}, ${a.readyCarriers} ready carrier(s), tracking confidence ${a.trackingConfidence}%, carrier-ready score ${a.carrierScore}. ${a.carrierReason}`).join('\n')}\n\n## Monetization angle`);};
const __h4LoadboardBaseUpdate=updateOutputs;
updateOutputs=function(){__h4LoadboardBaseUpdate(); const audit=carrierReadyAudit(); const thin=audit.filter(a=>a.carrierStatus!=='ready'); if($('carrierSummary'))$('carrierSummary').textContent=`${thin.length} thin/blocked · ${audit.length} lanes checked`; if($('carrierRows'))$('carrierRows').innerHTML=audit.map(a=>`<article class="floor-card"><h3>${a.id}</h3><p>${a.origin} → ${a.destination} · ${a.equipment}</p><strong>${a.readyCarriers} ready</strong><p>Carrier-ready score ${a.carrierScore} · tracking ${a.trackingConfidence}%</p><span class="pill ${a.carrierStatus==='ready'?'good':a.carrierStatus==='thin'?'warn':'bad'}">${a.carrierStatus}</span></article>`).join(''); if($('brief'))$('brief').value=brief(); save();};
const __h4LoadboardBaseRender=render;
render=function(){__h4LoadboardBaseRender(); if(state.carrierReadyMin===undefined)state.carrierReadyMin=3; const ctl=$('carrierReadyMin'); if(ctl)ctl.value=state.carrierReadyMin;};
if(state.carrierReadyMin===undefined)state.carrierReadyMin=3;
const __h4CarrierCtl=$('carrierReadyMin'); if(__h4CarrierCtl)__h4CarrierCtl.addEventListener('input',()=>{state.carrierReadyMin=__h4CarrierCtl.value;save();updateOutputs();});
$('downloadJson').onclick=()=>download('loadboard-signal-console.json',JSON.stringify({settings:{targetOrigin:state.targetOrigin,targetDestination:state.targetDestination,minMargin:state.minMargin,maxDeadhead:state.maxDeadhead,riskTolerance:state.riskTolerance,floorRpm:state.floorRpm,targetMargin:state.targetMargin,floorSeverity:state.floorSeverity,laneShareLimit:state.laneShareLimit,carrierReadyMin:state.carrierReadyMin},loads:state.loads,ranked:ranked(),floorAudit:floorAudit(),exposureAudit:exposureAudit(),carrierReadyAudit:carrierReadyAudit(),brief:brief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('loadboard-signal-console.csv',['id,origin,destination,equipment,miles,deadhead,sell,buy,gross,margin,score,risk,suggested_sell,ask_gap,lane_bucket_share,ready_carriers,carrier_status,carrier_ready_score',...ranked().map(l=>{const bucket=exposureAudit().find(e=>e.ids.includes(l.id));const carrier=carrierReadyAudit().find(a=>a.id===l.id)||{};return [l.id,l.origin,l.destination,l.equipment,l.miles,l.deadhead,l.sell,l.buy,l.gross,l.margin.toFixed(1),l.score,l.risk,l.suggestedSell,l.askGap,bucket?bucket.share.toFixed(1):0,carrier.readyCarriers||0,carrier.carrierStatus||'',carrier.carrierScore||0].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')})].join('\n'),'text/csv');

/* Hour 05 cumulative enhancement: tender readiness gate for loadboard rows. */
function tenderReadinessAudit(){
  const min=num(state.tenderReadinessMin||75); const carrier=typeof carrierReadyAudit==='function'?carrierReadyAudit():[];
  return ranked().map(l=>{const c=carrier.find(x=>x.id===l.id)||{}; const facts=[l.id,l.origin,l.destination,l.equipment,l.miles,l.sell,l.buy].filter(Boolean).length; const marginOk=l.margin>=num(state.minMargin); const priceOk=!l.belowFloor; const carrierOk=(c.readyCarriers||0)>=num(state.carrierReadyMin||3); const riskOk=l.risk!=='high'; const score=Math.round((facts/7*25)+(marginOk?20:0)+(priceOk?20:0)+(carrierOk?20:0)+(riskOk?15:5)); const status=score>=min?'packet-ready':score>=min-18?'needs review':'blocked'; const missing=[]; if(!marginOk)missing.push('margin below floor'); if(!priceOk)missing.push('ask floor not cleared'); if(!carrierOk)missing.push('carrier pool thin'); if(!riskOk)missing.push('high risk row'); return {...l,tenderScore:Math.max(0,Math.min(100,score)),tenderStatus:status,tenderMissing:missing.length?missing:['ready facts captured']};}).sort((a,b)=>a.tenderScore-b.tenderScore||b.askGap-a.askGap);
}
const __h5LoadboardBaseBrief=brief;
brief=function(){const base=__h5LoadboardBaseBrief(); const audit=tenderReadinessAudit(); return base.replace('\n## Monetization angle', `\n## Tender readiness gate\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.tenderStatus}, readiness ${a.tenderScore}%, blockers/checks: ${a.tenderMissing.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h5LoadboardBaseUpdate=updateOutputs;
updateOutputs=function(){__h5LoadboardBaseUpdate(); const audit=tenderReadinessAudit(); const review=audit.filter(a=>a.tenderStatus!=='packet-ready'); if($('tenderSummary'))$('tenderSummary').textContent=`${review.length} review/blocked · ${audit.length} loads checked`; if($('tenderRows'))$('tenderRows').innerHTML=audit.map(a=>`<article class="floor-card"><h3>${a.id}</h3><p>${a.origin} → ${a.destination} · ${a.equipment}</p><strong>${a.tenderScore}%</strong><p>${a.tenderMissing.join('; ')}</p><span class="pill ${a.tenderStatus==='packet-ready'?'good':a.tenderStatus==='needs review'?'warn':'bad'}">${a.tenderStatus}</span></article>`).join(''); if($('brief'))$('brief').value=brief(); save();};
const __h5LoadboardBaseRender=render;
render=function(){__h5LoadboardBaseRender(); if(state.tenderReadinessMin===undefined)state.tenderReadinessMin=75; const ctl=$('tenderReadinessMin'); if(ctl)ctl.value=state.tenderReadinessMin;};
if(state.tenderReadinessMin===undefined)state.tenderReadinessMin=75;
const __h5TenderCtl=$('tenderReadinessMin'); if(__h5TenderCtl)__h5TenderCtl.addEventListener('input',()=>{state.tenderReadinessMin=__h5TenderCtl.value;save();updateOutputs();});
$('downloadJson').onclick=()=>download('loadboard-signal-console.json',JSON.stringify({settings:{targetOrigin:state.targetOrigin,targetDestination:state.targetDestination,minMargin:state.minMargin,maxDeadhead:state.maxDeadhead,riskTolerance:state.riskTolerance,floorRpm:state.floorRpm,targetMargin:state.targetMargin,floorSeverity:state.floorSeverity,laneShareLimit:state.laneShareLimit,carrierReadyMin:state.carrierReadyMin,tenderReadinessMin:state.tenderReadinessMin},loads:state.loads,ranked:ranked(),floorAudit:floorAudit(),exposureAudit:exposureAudit(),carrierReadyAudit:carrierReadyAudit(),tenderReadinessAudit:tenderReadinessAudit(),brief:brief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('loadboard-signal-console.csv',['id,origin,destination,equipment,miles,deadhead,sell,buy,gross,margin,score,risk,suggested_sell,ask_gap,tender_score,tender_status',...ranked().map(l=>{const tender=tenderReadinessAudit().find(a=>a.id===l.id)||{};return [l.id,l.origin,l.destination,l.equipment,l.miles,l.deadhead,l.sell,l.buy,l.gross,l.margin.toFixed(1),l.score,l.risk,l.suggestedSell,l.askGap,tender.tenderScore||0,tender.tenderStatus||''].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')})].join('\n'),'text/csv');
/* Hour 06 cumulative enhancement: lifecycle stall forecast for loadboard rows. */
function lifecycleStallForecast(){
  const min=num(state.lifecycleConfidenceMin||68); const tender=typeof tenderReadinessAudit==='function'?tenderReadinessAudit():ranked();
  return ranked().map(l=>{const t=tender.find(x=>x.id===l.id)||{}; let score=48+Math.min(18,l.margin)+Math.min(12,Math.max(0,120-num(l.age))/10)-Math.min(15,num(l.deadhead)/20); if(l.risk==='high')score-=18; if(l.risk==='medium')score-=7; if(t.tenderScore)score+=(t.tenderScore-65)*0.28; if(l.belowFloor)score-=10; score=Math.max(0,Math.min(100,Math.round(score))); const blockers=[]; if(num(l.age)>90)blockers.push('stale posting'); if(l.belowFloor)blockers.push('quote floor gap'); if(l.risk==='high')blockers.push('high risk'); if((t.tenderStatus||'').includes('blocked'))blockers.push('tender blocked'); const status=score>=min?'lifecycle-ready':score>=min-18?'watch handoff':'stall risk'; return {...l,lifecycleScore:score,lifecycleStatus:status,lifecycleBlockers:blockers.length?blockers:['stage handoff looks clean']};}).sort((a,b)=>a.lifecycleScore-b.lifecycleScore||b.age-a.age);
}
const __h6LoadboardBaseBrief=brief;
brief=function(){const base=__h6LoadboardBaseBrief(); const audit=lifecycleStallForecast(); return base.replace('\n## Monetization angle', `\n## Lifecycle stall forecast\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.lifecycleStatus}, confidence ${a.lifecycleScore}%, checks: ${a.lifecycleBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h6LoadboardBaseUpdate=updateOutputs;
updateOutputs=function(){__h6LoadboardBaseUpdate(); const audit=lifecycleStallForecast(); const stalled=audit.filter(a=>a.lifecycleStatus!=='lifecycle-ready'); if($('lifecycleSummary'))$('lifecycleSummary').textContent=`${stalled.length} watch/stall · ${audit.length} rows checked`; if($('lifecycleRows'))$('lifecycleRows').innerHTML=audit.map(a=>`<article class="floor-card"><h3>${a.id}</h3><p>${a.origin} → ${a.destination} · age ${a.age} min</p><strong>${a.lifecycleScore}%</strong><p>${a.lifecycleBlockers.join('; ')}</p><span class="pill ${a.lifecycleStatus==='lifecycle-ready'?'good':a.lifecycleStatus==='watch handoff'?'warn':'bad'}">${a.lifecycleStatus}</span></article>`).join(''); if($('brief'))$('brief').value=brief(); save();};
const __h6LoadboardBaseRender=render;
render=function(){__h6LoadboardBaseRender(); if(state.lifecycleConfidenceMin===undefined)state.lifecycleConfidenceMin=68; const ctl=$('lifecycleConfidenceMin'); if(ctl)ctl.value=state.lifecycleConfidenceMin;};
if(state.lifecycleConfidenceMin===undefined)state.lifecycleConfidenceMin=68;
const __h6LifecycleCtl=$('lifecycleConfidenceMin'); if(__h6LifecycleCtl)__h6LifecycleCtl.addEventListener('input',()=>{state.lifecycleConfidenceMin=__h6LifecycleCtl.value;save();updateOutputs();});
$('downloadJson').onclick=()=>download('loadboard-signal-console.json',JSON.stringify({settings:{targetOrigin:state.targetOrigin,targetDestination:state.targetDestination,minMargin:state.minMargin,maxDeadhead:state.maxDeadhead,riskTolerance:state.riskTolerance,floorRpm:state.floorRpm,targetMargin:state.targetMargin,floorSeverity:state.floorSeverity,laneShareLimit:state.laneShareLimit,carrierReadyMin:state.carrierReadyMin,tenderReadinessMin:state.tenderReadinessMin,lifecycleConfidenceMin:state.lifecycleConfidenceMin},loads:state.loads,ranked:ranked(),floorAudit:floorAudit(),exposureAudit:exposureAudit(),carrierReadyAudit:carrierReadyAudit(),tenderReadinessAudit:tenderReadinessAudit(),lifecycleStallForecast:lifecycleStallForecast(),brief:brief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('loadboard-signal-console.csv',['id,origin,destination,equipment,miles,deadhead,sell,buy,gross,margin,score,risk,suggested_sell,ask_gap,tender_score,tender_status,lifecycle_score,lifecycle_status',...ranked().map(l=>{const tender=tenderReadinessAudit().find(a=>a.id===l.id)||{};const life=lifecycleStallForecast().find(a=>a.id===l.id)||{};return [l.id,l.origin,l.destination,l.equipment,l.miles,l.deadhead,l.sell,l.buy,l.gross,l.margin.toFixed(1),l.score,l.risk,l.suggestedSell,l.askGap,tender.tenderScore||0,tender.tenderStatus||'',life.lifecycleScore||0,life.lifecycleStatus||''].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')})].join('\n'),'text/csv');
/* Hour 07 cumulative enhancement: detention exposure audit for loadboard rows. */
function detentionExposureAudit(){
  const hourly=num(state.detentionReserveHourly||85);
  return ranked().map(l=>{const dwell=Math.max(0,1.25+num(l.deadhead)/140+num(l.age)/95+(l.risk==='high'?1.3:l.risk==='medium'?0.6:0)); const reserve=Math.round(Math.max(0,dwell-2)*hourly); const blockers=[]; if(dwell>2)blockers.push(`${dwell.toFixed(1)} hr dwell exposure`); if(num(l.age)>90)blockers.push('stale posting may hide appointment slop'); if(num(l.deadhead)>num(state.maxDeadhead))blockers.push('deadhead compresses appointment buffer'); if(l.risk!=='low')blockers.push(`${l.risk} lane risk`); const status=reserve>=220?'reserve required':reserve>0?'document dwell':'low exposure'; return {...l,detentionDwell:dwell,detentionReserve:reserve,detentionStatus:status,detentionBlockers:blockers.length?blockers:['inside dwell guardrail']};}).sort((a,b)=>b.detentionReserve-a.detentionReserve||b.score-a.score);
}
const __h7LoadboardBaseBrief=brief;
brief=function(){const base=__h7LoadboardBaseBrief(); const audit=detentionExposureAudit(); return base.replace('\n## Monetization angle', `\n## Detention exposure audit\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.detentionStatus}, reserve ${money(a.detentionReserve)}, checks: ${a.detentionBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h7LoadboardBaseUpdate=updateOutputs;
updateOutputs=function(){__h7LoadboardBaseUpdate(); const audit=detentionExposureAudit(); const review=audit.filter(a=>a.detentionStatus!=='low exposure'); if($('detentionSummary'))$('detentionSummary').textContent=`${review.length} reserve/document · ${audit.length} rows checked`; if($('detentionRows'))$('detentionRows').innerHTML=audit.map(a=>`<article class="floor-card"><h3>${a.id}</h3><p>${a.origin} → ${a.destination}</p><strong>${money(a.detentionReserve)}</strong><p>${a.detentionBlockers.join('; ')}</p><span class="pill ${a.detentionStatus==='low exposure'?'good':a.detentionStatus==='document dwell'?'warn':'bad'}">${a.detentionStatus}</span></article>`).join(''); if($('brief'))$('brief').value=brief(); save();};
const __h7LoadboardBaseRender=render;
render=function(){__h7LoadboardBaseRender(); if(state.detentionReserveHourly===undefined)state.detentionReserveHourly=85; const ctl=$('detentionReserveHourly'); if(ctl)ctl.value=state.detentionReserveHourly;};
if(state.detentionReserveHourly===undefined)state.detentionReserveHourly=85;
const __h7DetentionCtl=$('detentionReserveHourly'); if(__h7DetentionCtl)__h7DetentionCtl.addEventListener('input',()=>{state.detentionReserveHourly=__h7DetentionCtl.value;save();updateOutputs();});
$('downloadJson').onclick=()=>download('loadboard-signal-console.json',JSON.stringify({settings:{...state},loads:state.loads,ranked:ranked(),floorAudit:floorAudit(),exposureAudit:exposureAudit(),carrierReadyAudit:carrierReadyAudit(),tenderReadinessAudit:tenderReadinessAudit(),lifecycleStallForecast:lifecycleStallForecast(),detentionExposureAudit:detentionExposureAudit(),brief:brief(),safety:'local draft only'},null,2),'application/json');
/* Hour 08 cumulative enhancement: appointment fit audit for loadboard rows. */
function appointmentFitAudit(){return ranked().map(l=>{const slack=Math.max(0,10-num(l.deadhead)/42-num(l.age)/80-(l.risk==='high'?2:l.risk==='medium'?1:0)); const score=Math.max(0,Math.min(100,Math.round(52+slack*5-Math.max(0,num(l.deadhead)-num(state.maxDeadhead))*0.18-(l.belowFloor?8:0)))); const blockers=[]; if(num(l.deadhead)>num(state.maxDeadhead))blockers.push('deadhead compresses appointment window'); if(num(l.age)>90)blockers.push('stale post may hide appointment changes'); if(l.risk!=='low')blockers.push(`${l.risk} service risk`); if(l.belowFloor)blockers.push('quote floor gap before appointment hold'); const status=score>=76?'appointment-ready':score>=56?'window review':'appointment risk'; return {...l,appointmentSlack:slack,appointmentScore:score,appointmentStatus:status,appointmentBlockers:blockers.length?blockers:['window appears workable for broker review']};}).sort((a,b)=>a.appointmentScore-b.appointmentScore||b.age-a.age);}
const __h8LoadboardBaseBrief=brief;
brief=function(){const base=__h8LoadboardBaseBrief(); const audit=appointmentFitAudit(); return base.replace('\n## Monetization angle', `\n## Appointment fit audit\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.appointmentStatus}, appointment score ${a.appointmentScore}%, slack ${a.appointmentSlack.toFixed(1)} hr, checks: ${a.appointmentBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h8LoadboardBaseUpdate=updateOutputs;
updateOutputs=function(){__h8LoadboardBaseUpdate(); const audit=appointmentFitAudit(); const review=audit.filter(a=>a.appointmentStatus!=='appointment-ready'); if($('appointmentFitSummary'))$('appointmentFitSummary').textContent=`${review.length} review/risk · ${audit.length} rows checked`; if($('appointmentFitRows'))$('appointmentFitRows').innerHTML=audit.map(a=>`<article class="floor-card"><h3>${a.id}</h3><p>${a.origin} → ${a.destination}</p><strong>${a.appointmentScore}%</strong><p>${a.appointmentBlockers.join('; ')}</p><span class="pill ${a.appointmentStatus==='appointment-ready'?'good':a.appointmentStatus==='window review'?'warn':'bad'}">${a.appointmentStatus}</span></article>`).join(''); if($('brief'))$('brief').value=brief(); save();};
$('downloadJson').onclick=()=>download('loadboard-signal-console.json',JSON.stringify({settings:{...state},loads:state.loads,ranked:ranked(),floorAudit:floorAudit(),exposureAudit:exposureAudit(),carrierReadyAudit:carrierReadyAudit(),tenderReadinessAudit:tenderReadinessAudit(),lifecycleStallForecast:lifecycleStallForecast(),detentionExposureAudit:detentionExposureAudit(),appointmentFitAudit:appointmentFitAudit(),brief:brief(),safety:'local draft only'},null,2),'application/json');

/* Hour 09 cumulative enhancement: document precheck audit for loadboard rows. */
function documentPrecheckAudit(){return ranked().map(l=>{let score=88; const blockers=[]; if(l.belowFloor){score-=8; blockers.push('rate-con sell floor not cleared');} if(l.risk!=='low'){score-=l.risk==='high'?18:9; blockers.push(`${l.risk} risk needs document proof notes`);} if(num(l.age)>80){score-=10; blockers.push('stale posting requires refreshed rate/load facts');} if(num(l.deadhead)>num(state.maxDeadhead)){score-=8; blockers.push('deadhead exception should be documented');} if(String(l.notes||'').length<18){score-=7; blockers.push('notes too thin for packet handoff');} score=Math.max(0,Math.min(100,Math.round(score))); const status=score>=78?'docs-ready':score>=58?'doc review':'doc blocker'; return {...l,documentScore:score,documentStatus:status,documentBlockers:blockers.length?blockers:['rate con/BOL/POD packet looks document-ready']};}).sort((a,b)=>a.documentScore-b.documentScore||b.age-a.age);}
const __h9LoadboardBaseBrief=brief;
brief=function(){const base=__h9LoadboardBaseBrief(); const audit=documentPrecheckAudit(); return base.replace('\n## Monetization angle', `\n## Document precheck audit\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.documentStatus}, score ${a.documentScore}%, checks: ${a.documentBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h9LoadboardBaseUpdate=updateOutputs;
updateOutputs=function(){__h9LoadboardBaseUpdate(); const audit=documentPrecheckAudit(); const review=audit.filter(a=>a.documentStatus!=='docs-ready'); if($('documentPrecheckSummary'))$('documentPrecheckSummary').textContent=`${review.length} review/blocker · ${audit.length} rows checked`; if($('documentPrecheckRows'))$('documentPrecheckRows').innerHTML=audit.map(a=>`<article class="floor-card"><h3>${a.id}</h3><p>${a.origin} → ${a.destination}</p><strong>${a.documentScore}%</strong><p>${a.documentBlockers.join('; ')}</p><span class="pill ${a.documentStatus==='docs-ready'?'good':a.documentStatus==='doc review'?'warn':'bad'}">${a.documentStatus}</span></article>`).join(''); if($('brief'))$('brief').value=brief(); save();};
$('downloadJson').onclick=()=>download('loadboard-signal-console.json',JSON.stringify({settings:{...state},loads:state.loads,ranked:ranked(),floorAudit:floorAudit(),exposureAudit:exposureAudit(),carrierReadyAudit:carrierReadyAudit(),tenderReadinessAudit:tenderReadinessAudit(),lifecycleStallForecast:lifecycleStallForecast(),detentionExposureAudit:detentionExposureAudit(),appointmentFitAudit:appointmentFitAudit(),documentPrecheckAudit:documentPrecheckAudit(),brief:brief(),safety:'local draft only'},null,2),'application/json');

render();
