const STORAGE='detention-risk-calculator-v1';
const DEMO_CASES=[
  {id:'DT-7001',customer:'Blue River Foods',facility:'Blue River Chicago DC',facilityType:'shipper',lane:'Chicago, IL -> Atlanta, GA',appointment:'2026-07-14T08:00',arrivalOffsetMin:-20,plannedDwell:1.8,historicDwell:2.4,lateHistory:12,commodity:'Dry grocery',equipment:'Dry Van',terms:'2 hours free then detention billable with signed in/out times',notes:'Dock typically honors appointment but paperwork can lag.'},
  {id:'DT-7002',customer:'Ozark Retail',facility:'Ozark Dallas Grocery DC',facilityType:'receiver',lane:'Columbus, OH -> Dallas, TX',appointment:'2026-07-14T17:30',arrivalOffsetMin:55,plannedDwell:3.6,historicDwell:4.7,lateHistory:28,commodity:'Chilled retail',equipment:'Reefer',terms:'2 hours free, receiver approval needed for detention',notes:'After-hours reefer unload queue and lumper desk bottleneck.'},
  {id:'DT-7003',customer:'Summit Packaging',facility:'Summit Louisville Plant',facilityType:'receiver',lane:'Savannah, GA -> Louisville, KY',appointment:'2026-07-15T10:00',arrivalOffsetMin:10,plannedDwell:2.9,historicDwell:3.3,lateHistory:18,commodity:'Packaging',equipment:'Dry Van',terms:'No detention unless broker captures time stamps and BOL notes',notes:'Check-in line can run long during shift change.'},
  {id:'DT-7004',customer:'River City Supply',facility:'River City Memphis Yard',facilityType:'shipper',lane:'Memphis, TN -> Indianapolis, IN',appointment:'2026-07-15T06:00',arrivalOffsetMin:-35,plannedDwell:1.4,historicDwell:1.9,lateHistory:8,commodity:'Steel parts',equipment:'Flatbed',terms:'1.5 hours free, tarp delay excluded unless noted before departure',notes:'Yard loads quickly but securement/tarp inspection needs documentation.'}
];
const DEFAULTS={theme:'dark',freeHours:2,billRate:85,reservePct:70,graceMinutes:45,riskStance:'balanced',reviewThreshold:62,cases:DEMO_CASES};
const $=id=>document.getElementById(id); const num=v=>Number(v)||0; const money=n=>'$'+Math.round(num(n)).toLocaleString(); const pct=n=>`${Math.round(num(n))}%`; const clone=v=>JSON.parse(JSON.stringify(v));
let state=loadState();
function loadState(){try{return {...clone(DEFAULTS),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function escapeAttr(v){return String(v??'').replace(/"/g,'&quot;');}
function caseAudit(c){
  const stance=state.riskStance; const free=num(state.freeHours); const dwell=Math.max(num(c.plannedDwell),num(c.historicDwell)*0.72); const billable=Math.max(0,dwell-free); const late=Math.abs(num(c.arrivalOffsetMin))>num(state.graceMinutes); const latePenalty=late?12:0; const receiverPenalty=c.facilityType==='receiver'?7:0; const termText=String(c.terms||'').toLowerCase(); const termPenalty=termText.includes('approval')||termText.includes('no detention')?12:termText.includes('signed')?3:8; const reeferPenalty=c.equipment==='Reefer'?8:0; const historyPenalty=Math.min(24,num(c.lateHistory)*0.55); let score=Math.round(18+billable*16+historyPenalty+latePenalty+receiverPenalty+termPenalty+reeferPenalty); if(stance==='strict')score+=8; if(stance==='shipper-friendly')score-=8; score=Math.max(0,Math.min(100,score)); const exposure=billable*num(state.billRate); const reserve=exposure*num(state.reservePct)/100; const blockers=[]; if(billable>0)blockers.push(`${billable.toFixed(1)} billable dwell hr estimate`); if(late)blockers.push('appointment grace miss'); if(termPenalty>=8)blockers.push('terms/documentation friction'); if(num(c.lateHistory)>=20)blockers.push('repeat facility delay history'); if(c.equipment==='Reefer')blockers.push('reefer wait-cost sensitivity'); const status=score>=num(state.reviewThreshold)+18?'high exposure':score>=num(state.reviewThreshold)?'review':'controlled'; return {...c,dwell,billable,exposure,reserve,score,status,blockers:blockers.length?blockers:['inside configured detention guardrails'],late};
}
function audits(){return state.cases.map(caseAudit).sort((a,b)=>b.score-a.score||b.reserve-a.reserve);}
function facilityAudit(){const by={}; audits().forEach(a=>{const key=a.facility; by[key]=by[key]||{facility:a.facility,type:a.facilityType,count:0,score:0,reserve:0,late:0,ids:[]}; by[key].count++; by[key].score+=a.score; by[key].reserve+=a.reserve; by[key].late+=a.late?1:0; by[key].ids.push(a.id);}); return Object.values(by).map(f=>({...f,avgScore:Math.round(f.score/f.count),lateShare:f.late/f.count*100,status:(f.score/f.count)>=75?'facility watch':(f.score/f.count)>=55?'document tightly':'usable'})).sort((a,b)=>b.avgScore-a.avgScore);}
function rowEditor(c,i){const fields=['id','customer','facility','facilityType','lane','appointment','arrivalOffsetMin','plannedDwell','historicDwell','lateHistory','commodity','equipment','terms','notes']; return `<article class="case-card" data-i="${i}"><div class="case-grid">${fields.map(k=>{const label={arrivalOffsetMin:'arrival +/- min',plannedDwell:'planned dwell hr',historicDwell:'historic dwell hr',lateHistory:'late/delay %'}[k]||k; if(k==='facilityType')return `<label>${label}<select data-k="facilityType"><option ${c.facilityType==='shipper'?'selected':''}>shipper</option><option ${c.facilityType==='receiver'?'selected':''}>receiver</option><option ${c.facilityType==='crossdock'?'selected':''}>crossdock</option></select></label>`; if(k==='equipment')return `<label>${label}<select data-k="equipment"><option ${c.equipment==='Dry Van'?'selected':''}>Dry Van</option><option ${c.equipment==='Reefer'?'selected':''}>Reefer</option><option ${c.equipment==='Flatbed'?'selected':''}>Flatbed</option><option ${c.equipment==='Power Only'?'selected':''}>Power Only</option></select></label>`; const type=k==='appointment'?'datetime-local':['arrivalOffsetMin','plannedDwell','historicDwell','lateHistory'].includes(k)?'number':'text'; return `<label class="${['lane','appointment','terms','notes'].includes(k)?'wide':''}">${label}<input data-k="${k}" type="${type}" value="${escapeAttr(c[k])}"></label>`;}).join('')}</div><footer><span class="pill">case ${c.id}</span><button class="danger" data-remove="${i}">Remove</button></footer></article>`;}
function detentionBrief(){const list=audits(); const facilities=facilityAudit(); const total=list.reduce((s,a)=>s+a.reserve,0); const review=list.filter(a=>a.status!=='controlled'); const lines=['# Detention Risk Calculator brief','',`Generated: ${new Date().toLocaleString()}`,'Draft-only local detention estimate. Human broker approval is required before quoting, tendering, billing detention, contacting customers/carriers/facilities, writing TMS/CRM/EDI, using credentials, or spending money.','',`Estimated reserve exposure: ${money(total)}`,`Cases needing review: ${review.length}/${list.length}`,'', '## Case ranking']; list.forEach((a,i)=>lines.push(`${i+1}. ${a.id} ${a.customer} / ${a.facility}: ${a.status}, score ${a.score}, reserve ${money(a.reserve)}, billable dwell ${a.billable.toFixed(1)} hr. Checks: ${a.blockers.join('; ')}.`)); lines.push('', '## Facility profile audit'); facilities.forEach((f,i)=>lines.push(`${i+1}. ${f.facility}: ${f.status}, avg score ${f.avgScore}, reserve ${money(f.reserve)}, late share ${pct(f.lateShare)}, cases ${f.ids.join(', ')}.`)); lines.push('', '## Broker use','Use this before a quote or tender to decide whether to add a detention reserve, require signed in/out timestamps, tighten appointment language, or escalate facility terms for human review.', '', '## Safety boundary','No live scraping, facility/carrier/customer contact, load posting, dispatching, tendering, TMS/CRM/EDI writes, invoices, credential use, spend, or public/customer-facing action happens here.'); return lines.join('\n');}
function updateOutputs(){const list=audits(); const total=list.reduce((s,a)=>s+a.reserve,0); const review=list.filter(a=>a.status!=='controlled'); $('exposureTotal').textContent=money(total); $('exposureLabel').textContent=`${review.length} review case(s) · ${list.length} total`; $('brief').value=detentionBrief(); $('riskSummary').textContent=`${review.length} review/high · ${list.length} cases checked`; $('riskRows').innerHTML=list.map(a=>`<article class="result-card"><h3>${a.id} · ${a.facility}</h3><span class="pill ${a.status==='controlled'?'good':a.status==='review'?'warn':'bad'}">${a.status}</span><strong>${money(a.reserve)}</strong><p>Score ${a.score} · dwell ${a.dwell.toFixed(1)} hr · billable ${a.billable.toFixed(1)} hr.</p><p>${a.blockers.join('; ')}</p></article>`).join(''); const facilities=facilityAudit(); $('facilitySummary').textContent=`${facilities.length} facilities profiled`; $('facilityRows').innerHTML=facilities.map(f=>`<article class="result-card"><h3>${f.facility}</h3><span class="pill ${f.status==='usable'?'good':f.status==='document tightly'?'warn':'bad'}">${f.status}</span><strong>${f.avgScore}</strong><p>${f.type} · reserve ${money(f.reserve)} · late share ${pct(f.lateShare)}</p><p>${f.ids.join(', ')}</p></article>`).join(''); save();}
function render(){document.documentElement.dataset.theme=state.theme; $('themeToggle').textContent=state.theme==='light'?'Dark':'Light'; ['freeHours','billRate','reservePct','graceMinutes','riskStance','reviewThreshold'].forEach(k=>{$(k).value=state[k];}); $('caseCount').textContent=`${state.cases.length} cases`; $('caseRows').innerHTML=state.cases.map(rowEditor).join(''); document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const card=el.closest('.case-card'); state.cases[Number(card.dataset.i)][el.dataset.k]=el.value; save(); updateOutputs();})); document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{state.cases.splice(Number(btn.dataset.remove),1); save(); render(); toast('Case removed');})); updateOutputs();}
function toast(message){const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),1600);}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);}
function csv(){const header='id,customer,facility,type,lane,equipment,score,status,dwell_hours,billable_hours,reserve,blockers'; return [header,...audits().map(a=>[a.id,a.customer,a.facility,a.facilityType,a.lane,a.equipment,a.score,a.status,a.dwell.toFixed(1),a.billable.toFixed(1),a.reserve.toFixed(0),a.blockers.join('; ')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))].join('\n');}
['freeHours','billRate','reservePct','graceMinutes','riskStance','reviewThreshold'].forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value; save(); updateOutputs();}));
$('loadDemo').onclick=()=>{state={...clone(DEFAULTS),theme:state.theme}; render(); toast('Demo detention cases loaded');};
$('addCase').onclick=()=>{state.cases.push({id:`DT-${Date.now().toString().slice(-4)}`,customer:'Manual shipper',facility:'Manual facility',facilityType:'receiver',lane:'Origin -> Destination',appointment:'2026-07-16T09:00',arrivalOffsetMin:0,plannedDwell:2.5,historicDwell:3,lateHistory:15,commodity:'General freight',equipment:'Dry Van',terms:'2 hours free, signed in/out required',notes:'Manual detention candidate.'}); render(); toast('Case added');};
$('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light'; render();};
$('copyBrief').onclick=()=>navigator.clipboard?.writeText($('brief').value).then(()=>toast('Brief copied')).catch(()=>{$('brief').focus();$('brief').select();});
$('downloadJson').onclick=()=>download('detention-risk-calculator.json',JSON.stringify({controls:{freeHours:state.freeHours,billRate:state.billRate,reservePct:state.reservePct,graceMinutes:state.graceMinutes,riskStance:state.riskStance,reviewThreshold:state.reviewThreshold},cases:state.cases,audits:audits(),facilityAudit:facilityAudit(),brief:detentionBrief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('detention-risk-calculator.csv',csv(),'text/csv');
$('downloadMarkdown').onclick=()=>download('detention-risk-calculator.md',detentionBrief(),'text/markdown');
/* Hour 08 cumulative enhancement: appointment recovery playbook. */
function appointmentRecoveryPlaybook(){return audits().map(a=>{let urgency=0; if(a.late)urgency+=24; if(a.status!=='controlled')urgency+=18; if(a.billable>0)urgency+=Math.min(28,a.billable*10); if(num(a.lateHistory)>20)urgency+=14; if(String(a.terms||'').toLowerCase().includes('approval'))urgency+=10; const score=Math.max(0,Math.min(100,urgency)); const actions=[]; if(a.late)actions.push('call out appointment variance in broker notes'); if(a.billable>0)actions.push('capture signed in/out times before detention claim'); if(num(a.lateHistory)>20)actions.push('pre-book alternate appointment or add dwell buffer'); if(String(a.terms||'').toLowerCase().includes('approval'))actions.push('confirm approval path before billing detention'); const status=score>=58?'recovery plan needed':score>=28?'monitor appointment':'normal appointment'; return {...a,recoveryScore:score,recoveryStatus:status,recoveryActions:actions.length?actions:['normal arrival/dwell documentation']};}).sort((a,b)=>b.recoveryScore-a.recoveryScore||b.reserve-a.reserve);}
const __h8DetentionBaseBrief=detentionBrief;
detentionBrief=function(){const base=__h8DetentionBaseBrief(); const audit=appointmentRecoveryPlaybook(); return base.replace('\n## Broker use', `\n## Appointment recovery playbook\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.recoveryStatus}, urgency ${a.recoveryScore}%, actions: ${a.recoveryActions.join('; ')}.`).join('\n')}\n\n## Broker use`);};
const __h8DetentionBaseUpdate=updateOutputs;
updateOutputs=function(){__h8DetentionBaseUpdate(); const audit=appointmentRecoveryPlaybook(); const watch=audit.filter(a=>a.recoveryStatus!=='normal appointment'); if($('appointmentRecoverySummary'))$('appointmentRecoverySummary').textContent=`${watch.length} monitor/plan · ${audit.length} cases checked`; if($('appointmentRecoveryRows'))$('appointmentRecoveryRows').innerHTML=audit.map(a=>`<article class="result-card"><h3>${a.id} · ${a.facility}</h3><span class="pill ${a.recoveryStatus==='normal appointment'?'good':a.recoveryStatus==='monitor appointment'?'warn':'bad'}">${a.recoveryStatus}</span><strong>${a.recoveryScore}%</strong><p>${a.recoveryActions.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=detentionBrief(); save();};
$('downloadJson').onclick=()=>download('detention-risk-calculator.json',JSON.stringify({controls:{...state},cases:state.cases,audits:audits(),facilityAudit:facilityAudit(),appointmentRecoveryPlaybook:appointmentRecoveryPlaybook(),brief:detentionBrief(),safety:'local draft only'},null,2),'application/json');

/* Hour 09 cumulative enhancement: detention proof packet audit. */
function detentionProofPacketAudit(){return audits().map(a=>{let score=86; const blockers=[]; const text=String(a.terms+' '+a.notes).toLowerCase(); if(a.billable>0&&!/signed|timestamp|in\/out|bol|pod|approval/.test(text)){score-=22; blockers.push('billable dwell lacks proof language');} if(a.late){score-=10; blockers.push('late arrival variance needs appointment note');} if(a.status!=='controlled'){score-=12; blockers.push('case already needs review');} if(num(a.historicDwell)>num(state.freeHours)+2){score-=8; blockers.push('facility history needs stronger evidence packet');} if(String(a.terms||'').toLowerCase().includes('approval')){score-=5; blockers.push('approval path must be attached');} score=Math.max(0,Math.min(100,Math.round(score))); const status=score>=78?'proof-ready':score>=58?'proof review':'proof blocker'; return {...a,proofPacketScore:score,proofPacketStatus:status,proofPacketBlockers:blockers.length?blockers:['timestamp/BOL/POD proof posture appears ready']};}).sort((a,b)=>a.proofPacketScore-b.proofPacketScore||b.reserve-a.reserve);}
const __h9DetentionBaseBrief=detentionBrief;
detentionBrief=function(){const base=__h9DetentionBaseBrief(); const audit=detentionProofPacketAudit(); return base.replace('\n## Broker use', `\n## Detention proof packet audit\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.proofPacketStatus}, score ${a.proofPacketScore}%, checks: ${a.proofPacketBlockers.join('; ')}.`).join('\n')}\n\n## Broker use`);};
const __h9DetentionBaseUpdate=updateOutputs;
updateOutputs=function(){__h9DetentionBaseUpdate(); const audit=detentionProofPacketAudit(); const watch=audit.filter(a=>a.proofPacketStatus!=='proof-ready'); if($('detentionProofSummary'))$('detentionProofSummary').textContent=`${watch.length} review/blocker · ${audit.length} cases checked`; if($('detentionProofRows'))$('detentionProofRows').innerHTML=audit.map(a=>`<article class="result-card"><h3>${a.id} · ${a.facility}</h3><span class="pill ${a.proofPacketStatus==='proof-ready'?'good':a.proofPacketStatus==='proof review'?'warn':'bad'}">${a.proofPacketStatus}</span><strong>${a.proofPacketScore}%</strong><p>${a.proofPacketBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=detentionBrief(); save();};
$('downloadJson').onclick=()=>download('detention-risk-calculator.json',JSON.stringify({controls:{...state},cases:state.cases,audits:audits(),facilityAudit:facilityAudit(),appointmentRecoveryPlaybook:appointmentRecoveryPlaybook(),detentionProofPacketAudit:detentionProofPacketAudit(),brief:detentionBrief(),safety:'local draft only'},null,2),'application/json');

render();
