const STORAGE='appointment-window-optimizer-v1';
const DEMO_SCENARIOS=[
  {id:'AW-8001',customer:'Blue River Foods',lane:'Chicago, IL -> Atlanta, GA',equipment:'Dry Van',pickupWindow:'2026-07-14T08:00',deliveryWindow:'2026-07-15T09:00',originDwell:1.4,destDwell:1.8,deadhead:58,loadedMiles:716,facilityDelayPct:12,driverStart:'2026-07-14T06:30',marginDollars:450,notes:'Reliable shipper, normal morning dock queue.'},
  {id:'AW-8002',customer:'Ozark Retail',lane:'Columbus, OH -> Dallas, TX',equipment:'Reefer',pickupWindow:'2026-07-14T17:30',deliveryWindow:'2026-07-15T07:30',originDwell:2.7,destDwell:3.9,deadhead:142,loadedMiles:1064,facilityDelayPct:28,driverStart:'2026-07-14T07:00',marginDollars:545,notes:'After-hours reefer queue and tight unload request.'},
  {id:'AW-8003',customer:'Summit Packaging',lane:'Savannah, GA -> Louisville, KY',equipment:'Dry Van',pickupWindow:'2026-07-15T10:00',deliveryWindow:'2026-07-16T06:00',originDwell:2.3,destDwell:2.9,deadhead:210,loadedMiles:612,facilityDelayPct:22,driverStart:'2026-07-15T05:45',marginDollars:260,notes:'Port-adjacent appointment risk; thin gross.'},
  {id:'AW-8004',customer:'River City Supply',lane:'Memphis, TN -> Indianapolis, IN',equipment:'Flatbed',pickupWindow:'2026-07-15T06:00',deliveryWindow:'2026-07-15T15:30',originDwell:1.1,destDwell:1.6,deadhead:38,loadedMiles:463,facilityDelayPct:8,driverStart:'2026-07-15T05:00',marginDollars:265,notes:'Early pickup protects flatbed daylight unload.'}
];
const DEFAULTS={theme:'dark',driverDayHours:10,deadheadCap:125,dwellTarget:2,serviceBuffer:1.5,latePenaltyHourly:95,planningStance:'balanced',scenarios:DEMO_SCENARIOS};
const $=id=>document.getElementById(id); const num=v=>Number(v)||0; const money=n=>'$'+Math.round(num(n)).toLocaleString(); const pct=n=>`${Math.round(num(n))}%`; const clone=v=>JSON.parse(JSON.stringify(v));
let state=loadState();
function loadState(){try{return {...clone(DEFAULTS),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function escapeAttr(v){return String(v??'').replace(/"/g,'&quot;');}
function hoursBetween(a,b){const d=(new Date(b)-new Date(a))/36e5; return Number.isFinite(d)?d:0;}
function hourOf(v){const d=new Date(v); return Number.isFinite(d.getTime())?d.getHours()+d.getMinutes()/60:12;}
function scenarioAudit(s){
  const strict=state.planningStance==='strict'?1.2:state.planningStance==='opportunistic'?0.82:1;
  const totalDwell=num(s.originDwell)+num(s.destDwell);
  const driveHours=(num(s.deadhead)+num(s.loadedMiles))/52;
  const appointmentSpan=hoursBetween(s.pickupWindow,s.deliveryWindow);
  const availableAfterBuffer=Math.max(0,appointmentSpan-num(state.serviceBuffer));
  const clockPressure=driveHours/Math.max(1,num(state.driverDayHours))*100;
  const deadheadPressure=num(s.deadhead)/Math.max(1,num(state.deadheadCap))*100;
  const pickupHour=hourOf(s.pickupWindow); const deliveryHour=hourOf(s.deliveryWindow);
  const afterHours=(pickupHour<6||pickupHour>17||deliveryHour<6||deliveryHour>17);
  const dwellOver=Math.max(0,totalDwell-num(state.dwellTarget));
  const serviceSlack=availableAfterBuffer-driveHours-totalDwell;
  const lateCost=Math.max(0,dwellOver*num(state.latePenaltyHourly)+Math.max(0,-serviceSlack)*num(state.latePenaltyHourly));
  let score=92;
  score-=Math.max(0,deadheadPressure-70)*0.22*strict;
  score-=Math.max(0,clockPressure-85)*0.28*strict;
  score-=Math.max(0,num(s.facilityDelayPct)-12)*0.7*strict;
  score-=dwellOver*8*strict;
  score-=Math.max(0,-serviceSlack)*10*strict;
  if(afterHours)score-=7*strict;
  if(s.equipment==='Reefer')score-=4*strict;
  score=Math.max(0,Math.min(100,Math.round(score)));
  const blockers=[];
  if(num(s.deadhead)>num(state.deadheadCap))blockers.push('deadhead over cap');
  if(clockPressure>100)blockers.push('driver day over pressure');
  if(totalDwell>num(state.dwellTarget))blockers.push(`${totalDwell.toFixed(1)} dwell hr vs target`);
  if(serviceSlack<0)blockers.push(`${Math.abs(serviceSlack).toFixed(1)} hr service-buffer deficit`);
  if(num(s.facilityDelayPct)>20)blockers.push('facility delay history');
  if(afterHours)blockers.push('after-hours appointment exposure');
  const status=score>=78&&blockers.length<=1?'bookable window':score>=58?'revise window':'avoid window';
  const action=status==='bookable window'?'Hold this window for human broker confirmation.':status==='revise window'?'Move pickup/delivery time, widen service buffer, or add appointment-cost reserve.':'Do not use without revised appointment plan and human approval.';
  return {...s,totalDwell,driveHours,appointmentSpan,clockPressure,deadheadPressure,serviceSlack,lateCost,score,status,blockers:blockers.length?blockers:['inside appointment guardrails'],action};
}
function audits(){return state.scenarios.map(scenarioAudit).sort((a,b)=>b.score-a.score||a.lateCost-b.lateCost);}
function pressureAudit(){const list=audits(); const high=list.filter(a=>a.status!=='bookable window'); const totalCost=list.reduce((s,a)=>s+a.lateCost,0); const best=list[0]; return [
  {title:'Revision queue',value:`${high.length}/${list.length}`,tone:high.length?'warn':'good',body:high.length?`${high.map(h=>h.id).join(', ')} need appointment revision before use.`:'All appointment scenarios clear the configured guardrails.'},
  {title:'Potential late/dwell cost',value:money(totalCost),tone:totalCost?'warn':'good',body:'Estimated local reserve pressure from dwell over target and service-buffer deficits.'},
  {title:'Best protected window',value:best?best.id:'none',tone:best&&best.status==='bookable window'?'good':'warn',body:best?`${best.customer}: score ${best.score}, slack ${best.serviceSlack.toFixed(1)} hr, action: ${best.action}`:'Add scenarios to rank appointment windows.'},
  {title:'Human approval gate',value:'required',tone:'good',body:'This app only drafts appointment recommendations. A human broker must approve before operational action.'}
];}
function rowEditor(s,i){const fields=['id','customer','lane','equipment','pickupWindow','deliveryWindow','originDwell','destDwell','deadhead','loadedMiles','facilityDelayPct','driverStart','marginDollars','notes']; return `<article class="scenario-card" data-i="${i}"><div class="scenario-grid">${fields.map(k=>{const label={pickupWindow:'pickup appointment',deliveryWindow:'delivery appointment',originDwell:'origin dwell hr',destDwell:'dest dwell hr',facilityDelayPct:'facility delay %',driverStart:'driver start',marginDollars:'gross margin $'}[k]||k; if(k==='equipment')return `<label>${label}<select data-k="equipment"><option ${s.equipment==='Dry Van'?'selected':''}>Dry Van</option><option ${s.equipment==='Reefer'?'selected':''}>Reefer</option><option ${s.equipment==='Flatbed'?'selected':''}>Flatbed</option><option ${s.equipment==='Power Only'?'selected':''}>Power Only</option></select></label>`; const type=['pickupWindow','deliveryWindow','driverStart'].includes(k)?'datetime-local':['originDwell','destDwell','deadhead','loadedMiles','facilityDelayPct','marginDollars'].includes(k)?'number':'text'; const step=['originDwell','destDwell'].includes(k)?' step="0.1"':''; return `<label class="${['lane','notes'].includes(k)?'wide':''}">${label}<input data-k="${k}" type="${type}"${step} value="${escapeAttr(s[k])}"></label>`;}).join('')}</div><footer><span class="pill">${s.id}</span><button class="danger" data-remove="${i}">Remove</button></footer></article>`;}
function brokerBrief(){const list=audits(); const checks=pressureAudit(); const lines=['# Appointment Window Optimizer brief','',`Generated: ${new Date().toLocaleString()}`,'Draft-only local appointment planning output. Human broker approval is required before booking, revising, tendering, dispatching, contacting shippers/receivers/carriers, writing TMS/CRM/EDI, using credentials, or spending money.','',`Best window: ${list[0]?`${list[0].id} (${list[0].score}%)`:'none'}`,`Windows needing revision: ${list.filter(a=>a.status!=='bookable window').length}/${list.length}`,'','## Ranked appointment windows']; list.forEach((a,i)=>lines.push(`${i+1}. ${a.id} ${a.customer} / ${a.lane}: ${a.status}, score ${a.score}, slack ${a.serviceSlack.toFixed(1)} hr, dwell ${a.totalDwell.toFixed(1)} hr, clock pressure ${pct(a.clockPressure)}, late/dwell reserve ${money(a.lateCost)}. Checks: ${a.blockers.join('; ')}. Action: ${a.action}`)); lines.push('', '## Pressure audit'); checks.forEach(c=>lines.push(`- ${c.title}: ${c.value} — ${c.body}`)); lines.push('', '## Broker use','Use this before quoting or tendering to decide which appointment window protects driver clock, dwell, margin, service buffer, and facility delay risk. Export the brief for human review only.', '', '## Safety boundary','No live scraping, appointment booking, facility/carrier/customer contact, dispatching, tendering, TMS/CRM/EDI writes, credential use, spend, or public/customer-facing action happens here.'); return lines.join('\n');}
function updateOutputs(){const list=audits(); const best=list[0]; $('bestScore').textContent=best?pct(best.score):'0%'; $('bestLabel').textContent=best?`${best.id} · ${best.status}`:'Waiting for scenarios'; $('brief').value=brokerBrief(); $('rankingSummary').textContent=`${list.filter(a=>a.status!=='bookable window').length} revise/avoid · ${list.length} windows checked`; $('rankingRows').innerHTML=list.map(a=>`<article class="result-card"><h3>${a.id} · ${a.customer}</h3><span class="pill ${a.status==='bookable window'?'good':a.status==='revise window'?'warn':'bad'}">${a.status}</span><strong>${pct(a.score)}</strong><p>${a.lane}</p><p>Slack ${a.serviceSlack.toFixed(1)} hr · dwell ${a.totalDwell.toFixed(1)} hr · reserve ${money(a.lateCost)}</p><p>${a.blockers.join('; ')}</p></article>`).join(''); const checks=pressureAudit(); $('pressureSummary').textContent=`${checks.length} controls checked`; $('pressureRows').innerHTML=checks.map(c=>`<article class="result-card"><h3>${c.title}</h3><span class="pill ${c.tone}">${c.tone}</span><strong>${c.value}</strong><p>${c.body}</p></article>`).join(''); save();}
function render(){document.documentElement.dataset.theme=state.theme; $('themeToggle').textContent=state.theme==='light'?'Dark':'Light'; ['driverDayHours','deadheadCap','dwellTarget','serviceBuffer','latePenaltyHourly','planningStance'].forEach(k=>{$(k).value=state[k];}); $('scenarioCount').textContent=`${state.scenarios.length} scenarios`; $('scenarioRows').innerHTML=state.scenarios.map(rowEditor).join(''); document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const card=el.closest('.scenario-card'); state.scenarios[Number(card.dataset.i)][el.dataset.k]=el.value; save(); updateOutputs();})); document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{state.scenarios.splice(Number(btn.dataset.remove),1); save(); render(); toast('Scenario removed');})); updateOutputs();}
function toast(message){const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),1600);}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);}
function csv(){const header='rank,id,customer,lane,equipment,score,status,service_slack,dwell_hours,clock_pressure,deadhead,late_cost,blockers'; return [header,...audits().map((a,i)=>[i+1,a.id,a.customer,a.lane,a.equipment,a.score,a.status,a.serviceSlack.toFixed(1),a.totalDwell.toFixed(1),a.clockPressure.toFixed(1),a.deadhead,a.lateCost.toFixed(0),a.blockers.join('; ')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))].join('\n');}
['driverDayHours','deadheadCap','dwellTarget','serviceBuffer','latePenaltyHourly','planningStance'].forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value; save(); updateOutputs();}));
$('loadDemo').onclick=()=>{state={...clone(DEFAULTS),theme:state.theme}; render(); toast('Demo appointment windows loaded');};
$('addScenario').onclick=()=>{state.scenarios.push({id:`AW-${Date.now().toString().slice(-4)}`,customer:'Manual shipper',lane:'Origin -> Destination',equipment:'Dry Van',pickupWindow:'2026-07-16T08:00',deliveryWindow:'2026-07-17T09:00',originDwell:2,destDwell:2.5,deadhead:80,loadedMiles:650,facilityDelayPct:15,driverStart:'2026-07-16T06:00',marginDollars:400,notes:'Manual appointment candidate.'}); render(); toast('Scenario added');};
$('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light'; render();};
$('copyBrief').onclick=()=>navigator.clipboard?.writeText($('brief').value).then(()=>toast('Brief copied')).catch(()=>{$('brief').focus();$('brief').select();});
$('downloadJson').onclick=()=>download('appointment-window-optimizer.json',JSON.stringify({controls:{driverDayHours:state.driverDayHours,deadheadCap:state.deadheadCap,dwellTarget:state.dwellTarget,serviceBuffer:state.serviceBuffer,latePenaltyHourly:state.latePenaltyHourly,planningStance:state.planningStance},scenarios:state.scenarios,audits:audits(),pressureAudit:pressureAudit(),brief:brokerBrief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('appointment-window-optimizer.csv',csv(),'text/csv');
$('downloadMarkdown').onclick=()=>download('appointment-window-optimizer.md',brokerBrief(),'text/markdown');
/* Hour 09 cumulative enhancement: appointment document checklist. */
function appointmentDocumentChecklist(){return audits().map(a=>{let score=88; const blockers=[]; const text=String(a.notes||'').toLowerCase(); if(a.status!=='bookable window'){score-=14; blockers.push('appointment not yet bookable');} if(a.serviceSlack<1){score-=10; blockers.push('tight service slack needs appointment confirmation proof');} if(a.lateCost>0){score-=10; blockers.push('late/dwell reserve should be documented');} if(!/dock|appointment|check|queue|facility|arrival|unload|pickup/.test(text)){score-=8; blockers.push('facility/appointment note missing');} if(a.equipment==='Reefer'){score-=6; blockers.push('reefer appointment needs temp/load instructions attached');} score=Math.max(0,Math.min(100,Math.round(score))); const status=score>=78?'doc-confirmed':score>=58?'doc review':'doc blocker'; return {...a,appointmentDocScore:score,appointmentDocStatus:status,appointmentDocBlockers:blockers.length?blockers:['appointment confirmation notes are ready for packet']};}).sort((a,b)=>a.appointmentDocScore-b.appointmentDocScore||a.serviceSlack-b.serviceSlack);}
const __h9AppointmentBaseBrief=brokerBrief;
brokerBrief=function(){const base=__h9AppointmentBaseBrief(); const audit=appointmentDocumentChecklist(); return base.replace('\n## Broker use', `\n## Appointment document checklist\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.appointmentDocStatus}, score ${a.appointmentDocScore}%, checks: ${a.appointmentDocBlockers.join('; ')}.`).join('\n')}\n\n## Broker use`);};
const __h9AppointmentBaseUpdate=updateOutputs;
updateOutputs=function(){__h9AppointmentBaseUpdate(); const audit=appointmentDocumentChecklist(); const watch=audit.filter(a=>a.appointmentDocStatus!=='doc-confirmed'); if($('appointmentDocSummary'))$('appointmentDocSummary').textContent=`${watch.length} review/blocker · ${audit.length} scenarios checked`; if($('appointmentDocRows'))$('appointmentDocRows').innerHTML=audit.map(a=>`<article class="result-card"><h3>${a.id} · ${a.customer}</h3><span class="pill ${a.appointmentDocStatus==='doc-confirmed'?'good':a.appointmentDocStatus==='doc review'?'warn':'bad'}">${a.appointmentDocStatus}</span><strong>${a.appointmentDocScore}%</strong><p>${a.appointmentDocBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=brokerBrief(); save();};
$('downloadJson').onclick=()=>download('appointment-window-optimizer.json',JSON.stringify({controls:{...state},scenarios:state.scenarios,audits:audits(),pressureAudit:pressureAudit(),appointmentDocumentChecklist:appointmentDocumentChecklist(),brief:brokerBrief(),safety:'local draft only'},null,2),'application/json');

render();
