const STORAGE='load-lifecycle-command-board-v1';
const STAGES=['posted','covered','dispatched','picked','delivered','pod','invoiced','paid'];
const DEMO_LOADS=[
  {id:'LC-6001',customer:'Blue River Foods',lane:'Chicago, IL -> Atlanta, GA',equipment:'Dry Van',stage:'covered',pickupHours:9,deliveryHours:31,podAgeHours:0,invoiceAgeHours:0,paidAgeDays:0,sell:2525,buy:2075,carrier:'Great Lakes Linehaul',docs:'ratecon carrier-packet tracking',risk:'low',notes:'Covered with vetted carrier; dispatch confirmation due next.'},
  {id:'LC-6002',customer:'Ozark Retail',lane:'Columbus, OH -> Dallas, TX',equipment:'Reefer',stage:'posted',pickupHours:6,deliveryHours:28,podAgeHours:0,invoiceAgeHours:0,paidAgeDays:0,sell:3920,buy:3380,carrier:'unassigned',docs:'quote approval pending',risk:'medium',notes:'Pickup clock is tight; rate floor and reefer carrier check needed.'},
  {id:'LC-6003',customer:'Summit Packaging',lane:'Savannah, GA -> Louisville, KY',equipment:'Dry Van',stage:'delivered',pickupHours:0,deliveryHours:0,podAgeHours:19,invoiceAgeHours:0,paidAgeDays:0,sell:2250,buy:1990,carrier:'Peach State Freight',docs:'ratecon bol delivery-notes',risk:'high',notes:'Delivered; POD clock is running and margin is thin.'},
  {id:'LC-6004',customer:'River City Supply',lane:'Memphis, TN -> Indianapolis, IN',equipment:'Flatbed',stage:'invoiced',pickupHours:0,deliveryHours:0,podAgeHours:0,invoiceAgeHours:10,paidAgeDays:18,sell:1780,buy:1515,carrier:'Steel Ridge Flatbed',docs:'ratecon bol pod invoice',risk:'low',notes:'Invoice sent; watch customer pay clock and dispute notes.'}
];
const DEFAULTS={theme:'dark',stageFocus:'all',urgencyStance:'balanced',pickupSlaHours:18,podSlaHours:24,invoiceSlaHours:12,paidTargetDays:30,loads:DEMO_LOADS};
const $=id=>document.getElementById(id); const num=v=>Number(v)||0; const money=n=>'$'+Math.round(num(n)).toLocaleString(); const pct=n=>`${Math.round(num(n))}%`; const clone=v=>JSON.parse(JSON.stringify(v));
let state=loadState();
function loadState(){try{return {...clone(DEFAULTS),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function stageIndex(stage){return Math.max(0,STAGES.indexOf(stage));}
function margin(l){return num(l.sell)?(num(l.sell)-num(l.buy))/num(l.sell)*100:0;}
function stageAudit(l){
  const idx=stageIndex(l.stage); const strict=state.urgencyStance==='strict'; const cashFirst=state.urgencyStance==='cash-first';
  const docs=String(l.docs||'').toLowerCase(); const blockers=[]; let score=44+idx*6;
  if(l.stage==='posted' && num(l.pickupHours)<=num(state.pickupSlaHours))blockers.push('pickup clock');
  if(['delivered','pod'].includes(l.stage) && num(l.podAgeHours)>num(state.podSlaHours))blockers.push('POD overdue');
  if(l.stage==='pod' && num(l.invoiceAgeHours)>num(state.invoiceSlaHours))blockers.push('invoice overdue');
  if(['invoiced','paid'].includes(l.stage) && num(l.paidAgeDays)>num(state.paidTargetDays))blockers.push('pay clock');
  if(!docs.includes('ratecon'))blockers.push('rate con missing');
  if(idx>=3 && !docs.includes('bol'))blockers.push('BOL missing');
  if(idx>=5 && !docs.includes('pod'))blockers.push('POD missing');
  if(idx>=6 && !docs.includes('invoice'))blockers.push('invoice missing');
  if(margin(l)<14)blockers.push('thin margin');
  if(l.risk==='high')blockers.push('high risk');
  if(l.carrier==='unassigned')blockers.push('carrier unassigned');
  score += Math.min(20, margin(l));
  if(docs.includes('tracking'))score+=5; if(docs.includes('pod'))score+=8; if(docs.includes('invoice'))score+=8; if(l.carrier!=='unassigned')score+=8;
  score -= blockers.length*(strict?9:7); if(cashFirst && ['pod','invoiced'].includes(l.stage))score+=8;
  score=Math.max(0,Math.min(100,Math.round(score)));
  const status=score>=78?'on-track':score>=58?'watch':'exception';
  const next=STAGES[Math.min(STAGES.length-1,idx+1)];
  const action=blockers[0]?`Clear ${blockers[0]} before moving ${l.id} from ${l.stage} to ${next}.`:`Move ${l.id} toward ${next} after human broker confirmation.`;
  return {...l,margin:margin(l),lifecycleScore:score,lifecycleStatus:status,nextStage:next,blockers,action};
}
function auditedLoads(){return state.loads.map(stageAudit).sort((a,b)=>a.lifecycleScore-b.lifecycleScore||stageIndex(a.stage)-stageIndex(b.stage));}
function boardGroups(){const loads=auditedLoads(); return STAGES.map(stage=>({stage,loads:loads.filter(l=>l.stage===stage)}));}
function exceptions(){return auditedLoads().filter(l=>l.blockers.length||l.lifecycleStatus!=='on-track');}
function cashAudit(){return auditedLoads().map(l=>{const cashAtRisk=Math.max(0,num(l.sell)-num(l.buy)); let status='normal'; let note='No immediate cash/doc blocker.'; if(['delivered','pod'].includes(l.stage)&&l.blockers.includes('POD overdue')){status='pod chase'; note='POD clock is hurting invoice readiness.';} if(l.stage==='pod'&&l.blockers.includes('invoice overdue')){status='invoice now'; note='Invoice SLA missed after POD.';} if(l.stage==='invoiced'&&num(l.paidAgeDays)>=num(state.paidTargetDays)*0.75){status='cash watch'; note='Customer pay clock is nearing target.';} return {...l,cashAtRisk,cashStatus:status,cashNote:note};}).sort((a,b)=>b.cashAtRisk-a.cashAtRisk||b.paidAgeDays-a.paidAgeDays);}
function rowEditor(load,i){const fields=['id','customer','lane','equipment','stage','pickupHours','deliveryHours','podAgeHours','invoiceAgeHours','paidAgeDays','sell','buy','carrier','docs','risk','notes']; return `<article class="load-card" data-i="${i}"><div class="load-grid">${fields.map(k=>{const label={pickupHours:'pickup hours',deliveryHours:'delivery hours',podAgeHours:'POD age hours',invoiceAgeHours:'invoice age hours',paidAgeDays:'paid age days'}[k]||k; if(k==='stage')return `<label>${label}<select data-k="stage">${STAGES.map(s=>`<option ${load.stage===s?'selected':''}>${s}</option>`).join('')}</select></label>`; if(k==='equipment')return `<label>${label}<select data-k="equipment"><option ${load.equipment==='Dry Van'?'selected':''}>Dry Van</option><option ${load.equipment==='Reefer'?'selected':''}>Reefer</option><option ${load.equipment==='Flatbed'?'selected':''}>Flatbed</option><option ${load.equipment==='Power Only'?'selected':''}>Power Only</option></select></label>`; if(k==='risk')return `<label>${label}<select data-k="risk"><option ${load.risk==='low'?'selected':''}>low</option><option ${load.risk==='medium'?'selected':''}>medium</option><option ${load.risk==='high'?'selected':''}>high</option></select></label>`; const type=['pickupHours','deliveryHours','podAgeHours','invoiceAgeHours','paidAgeDays','sell','buy'].includes(k)?'number':'text'; return `<label class="${['lane','docs','notes'].includes(k)?'wide':''}">${label}<input data-k="${k}" type="${type}" value="${String(load[k]??'').replace(/"/g,'&quot;')}"></label>`;}).join('')}</div><footer><span class="pill">margin ${pct(margin(load))}</span><span class="pill">${load.stage}</span><button class="danger" data-remove="${i}">Remove</button></footer></article>`;}
function renderBoard(){const groups=boardGroups(); const filtered=state.stageFocus==='all'?groups:groups.filter(g=>g.stage===state.stageFocus); $('boardSummary').textContent=`${filtered.length} shown · ${state.loads.length} loads`; $('stageBoard').innerHTML=filtered.map(g=>`<section class="stage-col"><h3>${g.stage}</h3>${g.loads.length?g.loads.map(l=>`<article class="stage-load"><strong>${l.id}</strong><small>${l.customer}<br>${l.lane}</small><p><span class="pill ${l.lifecycleStatus==='on-track'?'good':l.lifecycleStatus==='watch'?'warn':'bad'}">${l.lifecycleScore}% ${l.lifecycleStatus}</span></p><p>${l.action}</p></article>`).join(''):'<p class="boundary">No loads in this stage.</p>'}</section>`).join('');}
function lifecycleBrief(){const loads=auditedLoads(); const ex=exceptions(); const cash=cashAudit(); const lines=['# Load Lifecycle Command Board brief','',`Generated: ${new Date().toLocaleString()}`,'Draft-only local operations board. Human broker approval is required before dispatching, contacting carriers/customers, writing TMS/CRM/EDI, posting freight, using credentials, or spending money.','',`Lifecycle health: ${overallHealth()}%`,`Open exceptions: ${ex.length}`,'', '## Priority loads']; loads.forEach((l,i)=>lines.push(`${i+1}. ${l.id} ${l.customer}: ${l.stage} -> ${l.nextStage}, score ${l.lifecycleScore} (${l.lifecycleStatus}), margin ${pct(l.margin)}, blockers: ${l.blockers.length?l.blockers.join('; '):'none'}. Action: ${l.action}`)); lines.push('', '## Cash and document clock'); cash.slice(0,6).forEach(c=>lines.push(`- ${c.id}: ${c.cashStatus}, ${money(c.cashAtRisk)} gross at risk. ${c.cashNote}`)); lines.push('', '## Monetization angle','Package this as the operational command layer for Backhaul: every load has a stage, score, exception reason, document/cash clock, and next-action brief before any broker updates live systems.', '', '## Safety boundary','No live scraping, load posting, dispatching, carrier/customer contact, TMS/CRM/EDI writes, credential use, spend, or public/customer-facing action happens here.'); return lines.join('\n');}
function overallHealth(){const loads=auditedLoads(); return loads.length?Math.round(loads.reduce((s,l)=>s+l.lifecycleScore,0)/loads.length):0;}
function updateOutputs(){const loads=auditedLoads(); const ex=exceptions(); const cash=cashAudit(); const health=overallHealth(); $('healthScore').textContent=pct(health); $('healthLabel').textContent=`${ex.length} exception(s) · ${loads.length} loads`; $('brief').value=lifecycleBrief(); renderBoard(); $('exceptionSummary').textContent=`${ex.length} loads need action`; $('exceptionRows').innerHTML=(ex.length?ex:loads).map(l=>`<article class="audit-card"><h3>${l.id} · ${l.stage}</h3><span class="pill ${l.lifecycleStatus==='on-track'?'good':l.lifecycleStatus==='watch'?'warn':'bad'}">${l.lifecycleStatus}</span><p>${l.blockers.length?l.blockers.join('; '):'No blockers.'}</p><p>${l.action}</p></article>`).join(''); const cashBlockers=cash.filter(c=>c.cashStatus!=='normal'); $('cashSummary').textContent=`${cashBlockers.length} cash/doc blockers`; $('cashRows').innerHTML=cash.slice(0,8).map(c=>`<article class="audit-card"><h3>${c.id} · ${c.customer}</h3><span class="pill ${c.cashStatus==='normal'?'good':c.cashStatus==='cash watch'?'warn':'bad'}">${c.cashStatus}</span><p>${money(c.cashAtRisk)} gross at risk · paid age ${c.paidAgeDays} day(s).</p><p>${c.cashNote}</p></article>`).join(''); save();}
function render(){document.documentElement.dataset.theme=state.theme; $('themeToggle').textContent=state.theme==='light'?'Dark':'Light'; ['stageFocus','urgencyStance','pickupSlaHours','podSlaHours','invoiceSlaHours','paidTargetDays'].forEach(k=>{$(k).value=state[k];}); $('loadCount').textContent=`${state.loads.length} loads`; $('loadRows').innerHTML=state.loads.map(rowEditor).join(''); document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const card=el.closest('.load-card'); state.loads[Number(card.dataset.i)][el.dataset.k]=el.value; save(); updateOutputs();})); document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{state.loads.splice(Number(btn.dataset.remove),1); save(); render(); toast('Load removed');})); updateOutputs();}
function toast(message){const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),1600);}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);}
function csv(){const header='id,customer,lane,equipment,stage,next_stage,lifecycle_score,status,margin,blockers,cash_status,gross_at_risk'; return [header,...auditedLoads().map(l=>{const c=cashAudit().find(x=>x.id===l.id)||{}; return [l.id,l.customer,l.lane,l.equipment,l.stage,l.nextStage,l.lifecycleScore,l.lifecycleStatus,l.margin.toFixed(1),l.blockers.join('; '),c.cashStatus||'',c.cashAtRisk||0].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')})].join('\n');}
['stageFocus','urgencyStance','pickupSlaHours','podSlaHours','invoiceSlaHours','paidTargetDays'].forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value; save(); updateOutputs();}));
$('loadDemo').onclick=()=>{state={...clone(DEFAULTS),theme:state.theme}; render(); toast('Demo lifecycle board loaded');};
$('addLoad').onclick=()=>{state.loads.push({id:`LC-${Date.now().toString().slice(-4)}`,customer:'Manual shipper',lane:'Origin -> Destination',equipment:'Dry Van',stage:'posted',pickupHours:12,deliveryHours:36,podAgeHours:0,invoiceAgeHours:0,paidAgeDays:0,sell:2200,buy:1850,carrier:'unassigned',docs:'quote pending',risk:'medium',notes:'Manual lifecycle candidate.'}); render(); toast('Load added');};
$('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light'; render();};
$('copyBrief').onclick=()=>navigator.clipboard?.writeText($('brief').value).then(()=>toast('Brief copied')).catch(()=>{$('brief').focus();$('brief').select();});
$('downloadJson').onclick=()=>download('load-lifecycle-command-board.json',JSON.stringify({controls:{stageFocus:state.stageFocus,urgencyStance:state.urgencyStance,pickupSlaHours:state.pickupSlaHours,podSlaHours:state.podSlaHours,invoiceSlaHours:state.invoiceSlaHours,paidTargetDays:state.paidTargetDays},loads:state.loads,auditedLoads:auditedLoads(),exceptions:exceptions(),cashAudit:cashAudit(),brief:lifecycleBrief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('load-lifecycle-command-board.csv',csv(),'text/csv');
$('downloadMarkdown').onclick=()=>download('load-lifecycle-command-board.md',lifecycleBrief(),'text/markdown');
/* Hour 07 cumulative enhancement: detention escalation clock. */
function detentionEscalationAudit(){
  const threshold=num(state.detentionEscalationHours||3);
  return auditedLoads().map(l=>{let dwell=0; if(l.stage==='posted')dwell=Math.max(0,num(l.pickupHours)*-1); if(['covered','dispatched','picked'].includes(l.stage))dwell=Math.max(0,threshold-(num(l.pickupHours)||threshold)); if(['delivered','pod'].includes(l.stage))dwell=Math.max(0,num(l.podAgeHours)/8); const reserve=Math.round(Math.max(0,dwell-2)*90); const blockers=[]; if(dwell>=threshold)blockers.push('dwell clock above escalation threshold'); if(l.blockers.includes('POD overdue'))blockers.push('POD delay may mask detention proof'); if(l.risk==='high')blockers.push('high risk load'); if(String(l.docs||'').toLowerCase().indexOf('bol')<0)blockers.push('BOL/time-stamp proof missing'); const status=blockers.length>=2?'escalate detention':reserve>0?'watch dwell':'clear clock'; return {...l,detentionDwell:dwell,detentionReserve:reserve,detentionStatus:status,detentionBlockers:blockers.length?blockers:['no detention escalation needed']};}).sort((a,b)=>b.detentionReserve-a.detentionReserve||b.detentionDwell-a.detentionDwell);
}
const __h7LifecycleBaseBrief=lifecycleBrief;
lifecycleBrief=function(){const base=__h7LifecycleBaseBrief(); const audit=detentionEscalationAudit(); return base.replace('\n## Monetization angle', `\n## Detention escalation clock\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.detentionStatus}, reserve ${money(a.detentionReserve)}, checks: ${a.detentionBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h7LifecycleBaseUpdate=updateOutputs;
updateOutputs=function(){__h7LifecycleBaseUpdate(); const audit=detentionEscalationAudit(); const watch=audit.filter(a=>a.detentionStatus!=='clear clock'); if($('detentionEscalationSummary'))$('detentionEscalationSummary').textContent=`${watch.length} watch/escalate · ${audit.length} loads checked`; if($('detentionEscalationRows'))$('detentionEscalationRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.id} · ${a.stage}</h3><span class="pill ${a.detentionStatus==='clear clock'?'good':a.detentionStatus==='watch dwell'?'warn':'bad'}">${a.detentionStatus}</span><p>Reserve ${money(a.detentionReserve)} · dwell ${a.detentionDwell.toFixed(1)} hr</p><p>${a.detentionBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=lifecycleBrief(); save();};
const __h7LifecycleBaseRender=render;
render=function(){__h7LifecycleBaseRender(); if(state.detentionEscalationHours===undefined)state.detentionEscalationHours=3; const ctl=$('detentionEscalationHours'); if(ctl)ctl.value=state.detentionEscalationHours;};
if(state.detentionEscalationHours===undefined)state.detentionEscalationHours=3;
const __h7EscalationCtl=$('detentionEscalationHours'); if(__h7EscalationCtl)__h7EscalationCtl.addEventListener('input',()=>{state.detentionEscalationHours=__h7EscalationCtl.value;save();updateOutputs();});
$('downloadJson').onclick=()=>download('load-lifecycle-command-board.json',JSON.stringify({controls:{...state},loads:state.loads,auditedLoads:auditedLoads(),exceptions:exceptions(),cashAudit:cashAudit(),detentionEscalationAudit:detentionEscalationAudit(),brief:lifecycleBrief(),safety:'local draft only'},null,2),'application/json');
/* Hour 08 cumulative enhancement: appointment miss triage. */
function appointmentMissTriageAudit(){return auditedLoads().map(l=>{let risk=0; if(l.stage==='posted'&&num(l.pickupHours)<=num(state.pickupSlaHours))risk+=22; if(['covered','dispatched'].includes(l.stage)&&num(l.pickupHours)<=6)risk+=24; if(['picked','delivered'].includes(l.stage)&&num(l.deliveryHours)<=4)risk+=18; if(l.blockers.includes('carrier unassigned'))risk+=18; if(l.risk==='high')risk+=16; if(String(l.docs||'').toLowerCase().indexOf('tracking')<0)risk+=10; const score=Math.max(0,Math.min(100,100-risk)); const blockers=[]; if(risk>=22)blockers.push('appointment clock pressure'); if(l.blockers.includes('carrier unassigned'))blockers.push('carrier not assigned'); if(l.risk==='high')blockers.push('high-risk load'); if(String(l.docs||'').toLowerCase().indexOf('tracking')<0)blockers.push('tracking proof missing'); const status=score>=78?'appointment-safe':score>=58?'miss watch':'miss risk'; return {...l,appointmentMissScore:score,appointmentMissStatus:status,appointmentMissBlockers:blockers.length?blockers:['appointment clock looks safe']};}).sort((a,b)=>a.appointmentMissScore-b.appointmentMissScore||stageIndex(a.stage)-stageIndex(b.stage));}
const __h8LifecycleBaseBrief=lifecycleBrief;
lifecycleBrief=function(){const base=__h8LifecycleBaseBrief(); const audit=appointmentMissTriageAudit(); return base.replace('\n## Monetization angle', `\n## Appointment miss triage\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.appointmentMissStatus}, score ${a.appointmentMissScore}%, checks: ${a.appointmentMissBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h8LifecycleBaseUpdate=updateOutputs;
updateOutputs=function(){__h8LifecycleBaseUpdate(); const audit=appointmentMissTriageAudit(); const watch=audit.filter(a=>a.appointmentMissStatus!=='appointment-safe'); if($('appointmentMissSummary'))$('appointmentMissSummary').textContent=`${watch.length} watch/risk · ${audit.length} loads checked`; if($('appointmentMissRows'))$('appointmentMissRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.id} · ${a.stage}</h3><span class="pill ${a.appointmentMissStatus==='appointment-safe'?'good':a.appointmentMissStatus==='miss watch'?'warn':'bad'}">${a.appointmentMissStatus}</span><p>Score ${a.appointmentMissScore}% · ${a.appointmentMissBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=lifecycleBrief(); save();};
$('downloadJson').onclick=()=>download('load-lifecycle-command-board.json',JSON.stringify({controls:{...state},loads:state.loads,auditedLoads:auditedLoads(),exceptions:exceptions(),cashAudit:cashAudit(),detentionEscalationAudit:detentionEscalationAudit(),appointmentMissTriageAudit:appointmentMissTriageAudit(),brief:lifecycleBrief(),safety:'local draft only'},null,2),'application/json');

/* Hour 09 cumulative enhancement: POD invoice document chase. */
function podInvoiceDocumentChase(){return auditedLoads().map(l=>{let risk=0; const blockers=[]; const docText=String(l.docs||'').toLowerCase(); if(['delivered','POD','invoice','paid'].includes(l.stage)&&!docText.includes('pod')){risk+=24; blockers.push('POD missing from docs text');} if(l.stage==='POD'&&num(l.podAgeHours)>num(state.podSlaHours)){risk+=20; blockers.push('POD age over SLA');} if(l.stage==='invoice'&&num(l.invoiceAgeHours)>num(state.invoiceSlaHours)){risk+=18; blockers.push('invoice age over SLA');} if(docText.indexOf('bol')<0){risk+=10; blockers.push('BOL reference missing');} if(l.risk==='high'){risk+=10; blockers.push('high-risk lane needs stronger proof file');} const score=Math.max(0,Math.min(100,100-risk)); const status=score>=80?'doc-current':score>=58?'doc chase':'cash blocker'; return {...l,podChaseScore:score,podChaseStatus:status,podChaseBlockers:blockers.length?blockers:['POD/BOL/invoice proof looks current']};}).sort((a,b)=>a.podChaseScore-b.podChaseScore||stageIndex(b.stage)-stageIndex(a.stage));}
const __h9LifecycleBaseBrief=lifecycleBrief;
lifecycleBrief=function(){const base=__h9LifecycleBaseBrief(); const audit=podInvoiceDocumentChase(); return base.replace('\n## Monetization angle', `\n## POD invoice document chase\n${audit.map((a,i)=>`${i+1}. ${a.id}: ${a.podChaseStatus}, score ${a.podChaseScore}%, checks: ${a.podChaseBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h9LifecycleBaseUpdate=updateOutputs;
updateOutputs=function(){__h9LifecycleBaseUpdate(); const audit=podInvoiceDocumentChase(); const watch=audit.filter(a=>a.podChaseStatus!=='doc-current'); if($('podChaseSummary'))$('podChaseSummary').textContent=`${watch.length} chase/blocker · ${audit.length} loads checked`; if($('podChaseRows'))$('podChaseRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.id} · ${a.stage}</h3><span class="pill ${a.podChaseStatus==='doc-current'?'good':a.podChaseStatus==='doc chase'?'warn':'bad'}">${a.podChaseStatus}</span><p>Score ${a.podChaseScore}% · ${a.podChaseBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=lifecycleBrief(); save();};
$('downloadJson').onclick=()=>download('load-lifecycle-command-board.json',JSON.stringify({controls:{...state},loads:state.loads,auditedLoads:auditedLoads(),exceptions:exceptions(),cashAudit:cashAudit(),detentionEscalationAudit:detentionEscalationAudit(),appointmentMissTriageAudit:appointmentMissTriageAudit(),podInvoiceDocumentChase:podInvoiceDocumentChase(),brief:lifecycleBrief(),safety:'local draft only'},null,2),'application/json');

render();
