const STORAGE='carrier-vetting-radar-v1';
const DEMO_CARRIERS=[
  {id:'MC-458201',name:'Great Lakes Linehaul',home:'Chicago, IL',lanes:'IL-GA,IL-TN,OH-GA',equipment:'Dry Van',safety:91,insurance:1.5,tracking:94,onTime:92,fraud:'none',authorityMonths:86,status:'approved',notes:'Strong southeast coverage, clean tracking cadence.'},
  {id:'MC-771904',name:'Peach State Freight',home:'Macon, GA',lanes:'GA-IL,GA-KY,AL-TN',equipment:'Dry Van',safety:84,insurance:1.0,tracking:88,onTime:86,fraud:'watch',authorityMonths:34,status:'review',notes:'Good reload density but identity docs need broker review.'},
  {id:'MC-229118',name:'Cold Chain Midwest',home:'Columbus, OH',lanes:'OH-TX,TX-MO,IL-GA',equipment:'Reefer',safety:89,insurance:2.0,tracking:90,onTime:84,fraud:'none',authorityMonths:58,status:'approved',notes:'Useful reefer bench; confirm temp recorder process.'},
  {id:'MC-640022',name:'Steel Ridge Flatbed',home:'Memphis, TN',lanes:'TN-IN,KY-IL,AL-TN',equipment:'Flatbed',safety:78,insurance:1.0,tracking:76,onTime:81,fraud:'none',authorityMonths:42,status:'approved',notes:'Flatbed option with moderate tracking discipline.'},
  {id:'MC-903551',name:'New Authority Express',home:'Savannah, GA',lanes:'GA-KY,GA-IL,SC-OH',equipment:'Dry Van',safety:61,insurance:0.75,tracking:66,onTime:68,fraud:'high',authorityMonths:5,status:'blocked',notes:'New authority, low insurance, high fraud signals; do not auto-use.'}
];
const DEFAULTS={theme:'dark',originState:'IL',destinationState:'GA',equipment:'Dry Van',minScore:72,minInsurance:1.0,fraudStance:'balanced',carriers:DEMO_CARRIERS};
const $=id=>document.getElementById(id); const num=v=>Number(v)||0; const pct=n=>`${Math.round(Number(n)||0)}%`; const money=n=>'$'+Number(n||0).toFixed(1)+'M';
function clone(v){return JSON.parse(JSON.stringify(v));}
let state=loadState();
function loadState(){try{return {...clone(DEFAULTS),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function laneFit(carrier){const lane=`${String(state.originState).toUpperCase()}-${String(state.destinationState).toUpperCase()}`; const reverse=`${String(state.destinationState).toUpperCase()}-${String(state.originState).toUpperCase()}`; const lanes=String(carrier.lanes||'').toUpperCase(); let score=lanes.includes(lane)?100:lanes.includes(reverse)?84:lanes.includes(String(state.destinationState).toUpperCase())?62:40; if(carrier.equipment!==state.equipment) score-=32; return Math.max(0,score);}
function fraudPenalty(carrier){const base=carrier.fraud==='high'?34:carrier.fraud==='watch'?15:0; const stance=state.fraudStance==='strict'?1.35:state.fraudStance==='opportunistic'?0.75:1; return base*stance;}
function scoreCarrier(carrier){const fit=laneFit(carrier); const insuranceOk=num(carrier.insurance)>=num(state.minInsurance); const ageScore=Math.min(100,num(carrier.authorityMonths)*2.4); let score=0; score+=fit*.24; score+=num(carrier.safety)*.23; score+=num(carrier.tracking)*.14; score+=num(carrier.onTime)*.16; score+=ageScore*.08; score+=(insuranceOk?100:35)*.10; score+=(carrier.status==='approved'?100:carrier.status==='review'?58:10)*.05; score-=fraudPenalty(carrier); const blockers=[]; if(carrier.equipment!==state.equipment) blockers.push('equipment mismatch'); if(!insuranceOk) blockers.push('insurance below minimum'); if(carrier.fraud==='high') blockers.push('high fraud signal'); if(carrier.status==='blocked') blockers.push('blocked status'); if(num(carrier.safety)<70) blockers.push('safety under 70'); if(num(carrier.authorityMonths)<12) blockers.push('authority under 12 months'); const approved=score>=num(state.minScore)&&blockers.length===0; return {...carrier,laneFit:fit,insuranceOk,score:Math.max(0,Math.min(99,Math.round(score))),blockers,approved};}
function ranked(){return state.carriers.map(scoreCarrier).sort((a,b)=>b.score-a.score||b.laneFit-a.laneFit||b.onTime-a.onTime)}
function blockerAudit(list=ranked()){const buckets={}; list.forEach(c=>{(c.blockers.length?c.blockers:['clear']).forEach(b=>{buckets[b]=buckets[b]||{label:b,count:0,ids:[],score:0}; buckets[b].count+=1; buckets[b].ids.push(c.id); buckets[b].score+=c.score;});}); return Object.values(buckets).map(b=>({...b,avg:b.count?b.score/b.count:0})).sort((a,b)=>b.count-a.count||a.avg-b.avg);}
function rowEditor(carrier,i){const fields=['id','name','home','lanes','equipment','safety','insurance','tracking','onTime','fraud','authorityMonths','status','notes']; return `<article class="carrier-card" data-i="${i}"><div class="carrier-grid">${fields.map(k=>{const label={authorityMonths:'authority months',onTime:'on-time %'}[k]||k; if(k==='equipment')return `<label>${label}<select data-k="equipment"><option ${carrier.equipment==='Dry Van'?'selected':''}>Dry Van</option><option ${carrier.equipment==='Reefer'?'selected':''}>Reefer</option><option ${carrier.equipment==='Flatbed'?'selected':''}>Flatbed</option><option ${carrier.equipment==='Power Only'?'selected':''}>Power Only</option></select></label>`; if(k==='fraud')return `<label>${label}<select data-k="fraud"><option ${carrier.fraud==='none'?'selected':''}>none</option><option ${carrier.fraud==='watch'?'selected':''}>watch</option><option ${carrier.fraud==='high'?'selected':''}>high</option></select></label>`; if(k==='status')return `<label>${label}<select data-k="status"><option ${carrier.status==='approved'?'selected':''}>approved</option><option ${carrier.status==='review'?'selected':''}>review</option><option ${carrier.status==='blocked'?'selected':''}>blocked</option></select></label>`; const type=['safety','insurance','tracking','onTime','authorityMonths'].includes(k)?'number':'text'; const step=k==='insurance'?' step="0.1"':''; return `<label class="${k==='notes'||k==='lanes'?'wide':''}">${label}<input data-k="${k}" type="${type}"${step} value="${String(carrier[k]??'').replace(/"/g,'&quot;')}"></label>`;}).join('')}</div><footer><span class="pill">${carrier.equipment}</span><span class="pill">${carrier.status}</span><button class="danger" data-remove="${i}">Remove</button></footer></article>`;}
function renderRankings(){const list=ranked(); const ready=list.filter(c=>c.approved); $('rankSummary').textContent=`${list.length} ranked · ${ready.length} ready`; $('readyCount').textContent=String(ready.length); $('readyLabel').textContent=ready[0]?`${ready[0].name} leads at ${ready[0].score}`:'No carrier clears the gate'; $('rankRows').innerHTML=list.map(c=>{const tone=c.approved?'good':c.score>=num(state.minScore)-8?'warn':'bad'; const blockers=c.blockers.length?c.blockers.join(', '):'clear for broker review'; return `<article class="rank-card"><div class="rank-title"><div>${c.name}</div><small>score ${c.score}</small></div><p class="route">${c.id} · ${c.home}<br>${c.lanes}</p><div class="tag-row"><span class="pill ${tone}">${c.approved?'approved-ready':'review gate'}</span><span class="pill">${blockers}</span></div><div class="metric-grid"><div class="metric"><span>lane fit</span><strong>${pct(c.laneFit)}</strong></div><div class="metric"><span>safety</span><strong>${pct(c.safety)}</strong></div><div class="metric"><span>insurance</span><strong>${money(c.insurance)}</strong></div><div class="metric"><span>tracking</span><strong>${pct(c.tracking)}</strong></div><div class="metric"><span>on-time</span><strong>${pct(c.onTime)}</strong></div><div class="metric"><span>authority</span><strong>${c.authorityMonths} mo</strong></div></div></article>`;}).join(''); renderAudit(list); $('brief').value=buildBrief(list);}
function renderAudit(list=ranked()){const audit=blockerAudit(list); const blockers=audit.filter(a=>a.label!=='clear'); $('auditSummary').textContent=`${blockers.reduce((s,a)=>s+a.count,0)} blockers · ${audit.length} buckets`; $('auditRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.label}</h3><span class="pill ${a.label==='clear'?'good':'warn'}">${a.count} carrier(s)</span><p>${a.ids.join(', ')}</p><p>Average vetting score ${a.avg.toFixed(0)}</p></article>`).join('');}
function buildBrief(list=ranked()){const ready=list.filter(c=>c.approved); const lines=['# Carrier Vetting Radar brief','',`Generated: ${new Date().toLocaleString()}`,'Draft-only local carrier-vetting model. Human broker approval is required before tendering, contacting carriers, writing TMS/CRM, posting freight, or spending money.','',`Target lane/equipment: ${state.originState.toUpperCase()} -> ${state.destinationState.toUpperCase()} / ${state.equipment}`,`Approved-ready carriers: ${ready.length} of ${list.length} at minimum score ${state.minScore} and insurance ${money(state.minInsurance)}.`,'', '## Ranked carrier bench']; list.forEach((c,i)=>lines.push(`${i+1}. ${c.name} (${c.id}): score ${c.score}, lane fit ${pct(c.laneFit)}, safety ${pct(c.safety)}, insurance ${money(c.insurance)}, tracking ${pct(c.tracking)}, on-time ${pct(c.onTime)}, authority ${c.authorityMonths} months, status ${c.status}${c.blockers.length?`, blockers: ${c.blockers.join('; ')}`:', clear for broker review'}. Notes: ${c.notes}`)); lines.push('', '## Approval blocker audit'); blockerAudit(list).forEach(a=>lines.push(`- ${a.label}: ${a.count} carrier(s), ids ${a.ids.join(', ')}, avg score ${a.avg.toFixed(0)}.`)); lines.push('', '## Monetization angle','Sell this as the carrier-risk module for Backhaul: it turns fragmented carrier notes into a repeatable approval gate before coverage, helping brokers reduce double-broker/fraud, insurance, tracking, and service-failure exposure.', '', '## Safety boundary','No live scraping, credential use, carrier contact, load posting, tendering, TMS/CRM writes, EDI/API calls, spend, or customer-facing commitments happen here.'); return lines.join('\n');}
function render(){document.documentElement.dataset.theme=state.theme; $('themeToggle').textContent=state.theme==='light'?'Dark':'Light'; ['originState','destinationState','equipment','minScore','minInsurance','fraudStance'].forEach(k=>{$(k).value=state[k];}); $('carrierCount').textContent=`${state.carriers.length} carriers`; $('carrierRows').innerHTML=state.carriers.map(rowEditor).join(''); document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const card=el.closest('.carrier-card'); state.carriers[Number(card.dataset.i)][el.dataset.k]=el.value; save(); renderRankings();})); document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{state.carriers.splice(Number(btn.dataset.remove),1); save(); render(); toast('Carrier removed');})); renderRankings(); save();}
function toast(message){const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),1600);}
function download(name,text,type){const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);}
function csv(){const header='rank,mc_id,name,home,lanes,equipment,score,approved,lane_fit,safety,insurance_m,tracking,on_time,fraud,authority_months,status,blockers'; return [header,...ranked().map((c,i)=>[i+1,c.id,c.name,c.home,c.lanes,c.equipment,c.score,c.approved,c.laneFit,c.safety,c.insurance,c.tracking,c.onTime,c.fraud,c.authorityMonths,c.status,c.blockers.join('; ')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))].join('\n');}
['originState','destinationState','equipment','minScore','minInsurance','fraudStance'].forEach(k=>$(k).addEventListener('input',()=>{state[k]=$(k).value; save(); renderRankings();}));
$('loadDemo').onclick=()=>{state={...clone(DEFAULTS),theme:state.theme}; render(); toast('Demo carriers loaded');};
$('addCarrier').onclick=()=>{state.carriers.push({id:`MC-${Date.now().toString().slice(-6)}`,name:'Manual Carrier',home:'New market',lanes:`${state.originState}-${state.destinationState}`,equipment:state.equipment,safety:78,insurance:1.0,tracking:80,onTime:82,fraud:'watch',authorityMonths:18,status:'review',notes:'Manual carrier candidate for broker review.'}); render(); toast('Carrier added');};
$('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light'; render();};
$('copyBrief').onclick=()=>navigator.clipboard?.writeText($('brief').value).then(()=>toast('Brief copied')).catch(()=>{$('brief').focus();$('brief').select();});
$('downloadJson').onclick=()=>download('carrier-vetting-radar.json',JSON.stringify({controls:{originState:state.originState,destinationState:state.destinationState,equipment:state.equipment,minScore:state.minScore,minInsurance:state.minInsurance,fraudStance:state.fraudStance},carriers:state.carriers,ranked:ranked(),blockerAudit:blockerAudit(),brief:buildBrief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('carrier-vetting-radar.csv',csv(),'text/csv');
/* Hour 05 cumulative enhancement: carrier document packet audit. */
function carrierPacketAudit(list=ranked()){
  const min=num(state.minDocCompleteness||80);
  return list.map(c=>{let score=30; if(c.status==='approved')score+=20; if(num(c.insurance)>=num(state.minInsurance))score+=18; if(num(c.authorityMonths)>=12)score+=12; if(num(c.tracking)>=80)score+=10; if(c.fraud==='none')score+=10; if(c.fraud==='high')score-=18; const missing=[]; if(c.status!=='approved')missing.push('approval status'); if(num(c.insurance)<num(state.minInsurance))missing.push('COI/insurance'); if(num(c.authorityMonths)<12)missing.push('authority age review'); if(num(c.tracking)<80)missing.push('tracking setup'); if(c.fraud!=='none')missing.push('identity/fraud review'); const complete=Math.max(0,Math.min(100,Math.round(score))); const status=complete>=min&&missing.length===0?'packet complete':complete>=min-20?'docs review':'blocked docs'; return {...c,docCompleteness:complete,docStatus:status,docMissing:missing.length?missing:['W9/COI/authority/tracking packet looks complete in mock data']};}).sort((a,b)=>a.docCompleteness-b.docCompleteness||b.score-a.score);
}
const __h5CarrierBaseBrief=buildBrief;
buildBrief=function(list=ranked()){const base=__h5CarrierBaseBrief(list); const audit=carrierPacketAudit(list); return base.replace('\n## Monetization angle', `\n## Carrier document packet audit\n${audit.map((a,i)=>`${i+1}. ${a.name}: ${a.docStatus}, completeness ${a.docCompleteness}%, missing/review: ${a.docMissing.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h5CarrierBaseRenderRankings=renderRankings;
renderRankings=function(){__h5CarrierBaseRenderRankings(); const audit=carrierPacketAudit(); const review=audit.filter(a=>a.docStatus!=='packet complete'); if($('docSummary'))$('docSummary').textContent=`${review.length} review/blocked · ${audit.length} carriers checked`; if($('docRows'))$('docRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.name}</h3><span class="pill ${a.docStatus==='packet complete'?'good':a.docStatus==='docs review'?'warn':'bad'}">${a.docCompleteness}%</span><p>${a.docStatus}: ${a.docMissing.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=buildBrief(); save();};
const __h5CarrierBaseRender=render;
render=function(){__h5CarrierBaseRender(); if(state.minDocCompleteness===undefined)state.minDocCompleteness=80; const ctl=$('minDocCompleteness'); if(ctl)ctl.value=state.minDocCompleteness;};
if(state.minDocCompleteness===undefined)state.minDocCompleteness=80;
const __h5DocCtl=$('minDocCompleteness'); if(__h5DocCtl)__h5DocCtl.addEventListener('input',()=>{state.minDocCompleteness=__h5DocCtl.value;save();renderRankings();});
$('downloadJson').onclick=()=>download('carrier-vetting-radar.json',JSON.stringify({controls:{originState:state.originState,destinationState:state.destinationState,equipment:state.equipment,minScore:state.minScore,minInsurance:state.minInsurance,fraudStance:state.fraudStance,minDocCompleteness:state.minDocCompleteness},carriers:state.carriers,ranked:ranked(),blockerAudit:blockerAudit(),carrierPacketAudit:carrierPacketAudit(),brief:buildBrief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('carrier-vetting-radar.csv',['rank,mc_id,name,home,lanes,equipment,score,approved,lane_fit,safety,insurance_m,tracking,on_time,fraud,authority_months,status,doc_completeness,doc_status,blockers',...ranked().map((c,i)=>{const d=carrierPacketAudit().find(x=>x.id===c.id)||{};return [i+1,c.id,c.name,c.home,c.lanes,c.equipment,c.score,c.approved,c.laneFit,c.safety,c.insurance,c.tracking,c.onTime,c.fraud,c.authorityMonths,c.status,d.docCompleteness||0,d.docStatus||'',c.blockers.join('; ')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')})].join('\n'),'text/csv');
/* Hour 06 cumulative enhancement: carrier lifecycle SLA readiness. */
function carrierLifecycleSlaAudit(list=ranked()){
  const min=num(state.minLifecycleSla||76);
  return list.map(c=>{let score=Math.round(num(c.onTime)*0.34+num(c.tracking)*0.28+num(c.safety)*0.18+Math.min(100,num(c.authorityMonths)*2)*0.08+(c.status==='approved'?12:c.status==='review'?4:0)); if(c.fraud==='watch')score-=7; if(c.fraud==='high')score-=22; if(c.docCompleteness)score+=(c.docCompleteness-75)*0.12; const blockers=[]; if(num(c.tracking)<80)blockers.push('tracking SLA'); if(num(c.onTime)<82)blockers.push('service SLA'); if(c.status!=='approved')blockers.push('approval'); if(c.fraud!=='none')blockers.push('fraud review'); score=Math.max(0,Math.min(100,Math.round(score))); const status=score>=min&&blockers.length===0?'lifecycle-ready':score>=min-15?'SLA watch':'SLA blocked'; return {...c,slaScore:score,slaStatus:status,slaBlockers:blockers.length?blockers:['dispatch/tracking/POD lifecycle looks usable']};}).sort((a,b)=>a.slaScore-b.slaScore||b.score-a.score);
}
const __h6CarrierBaseBrief=buildBrief;
buildBrief=function(list=ranked()){const base=__h6CarrierBaseBrief(list); const audit=carrierLifecycleSlaAudit(list); return base.replace('\n## Monetization angle', `\n## Carrier lifecycle SLA readiness\n${audit.map((a,i)=>`${i+1}. ${a.name}: ${a.slaStatus}, SLA score ${a.slaScore}%, blockers/checks: ${a.slaBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h6CarrierBaseRenderRankings=renderRankings;
renderRankings=function(){__h6CarrierBaseRenderRankings(); const audit=carrierLifecycleSlaAudit(); const watch=audit.filter(a=>a.slaStatus!=='lifecycle-ready'); if($('slaSummary'))$('slaSummary').textContent=`${watch.length} watch/blocked · ${audit.length} carriers checked`; if($('slaRows'))$('slaRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.name}</h3><span class="pill ${a.slaStatus==='lifecycle-ready'?'good':a.slaStatus==='SLA watch'?'warn':'bad'}">${a.slaScore}%</span><p>${a.slaStatus}: ${a.slaBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=buildBrief(); save();};
const __h6CarrierBaseRender=render;
render=function(){__h6CarrierBaseRender(); if(state.minLifecycleSla===undefined)state.minLifecycleSla=76; const ctl=$('minLifecycleSla'); if(ctl)ctl.value=state.minLifecycleSla;};
if(state.minLifecycleSla===undefined)state.minLifecycleSla=76;
const __h6SlaCtl=$('minLifecycleSla'); if(__h6SlaCtl)__h6SlaCtl.addEventListener('input',()=>{state.minLifecycleSla=__h6SlaCtl.value;save();renderRankings();});
$('downloadJson').onclick=()=>download('carrier-vetting-radar.json',JSON.stringify({controls:{originState:state.originState,destinationState:state.destinationState,equipment:state.equipment,minScore:state.minScore,minInsurance:state.minInsurance,fraudStance:state.fraudStance,minDocCompleteness:state.minDocCompleteness,minLifecycleSla:state.minLifecycleSla},carriers:state.carriers,ranked:ranked(),blockerAudit:blockerAudit(),carrierPacketAudit:carrierPacketAudit(),carrierLifecycleSlaAudit:carrierLifecycleSlaAudit(),brief:buildBrief(),safety:'local draft only'},null,2),'application/json');
$('downloadCsv').onclick=()=>download('carrier-vetting-radar.csv',['rank,mc_id,name,home,lanes,equipment,score,approved,lane_fit,safety,insurance_m,tracking,on_time,fraud,authority_months,status,doc_completeness,doc_status,sla_score,sla_status,blockers',...ranked().map((c,i)=>{const d=carrierPacketAudit().find(x=>x.id===c.id)||{};const s=carrierLifecycleSlaAudit().find(x=>x.id===c.id)||{};return [i+1,c.id,c.name,c.home,c.lanes,c.equipment,c.score,c.approved,c.laneFit,c.safety,c.insurance,c.tracking,c.onTime,c.fraud,c.authorityMonths,c.status,d.docCompleteness||0,d.docStatus||'',s.slaScore||0,s.slaStatus||'',c.blockers.join('; ')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')})].join('\n'),'text/csv');
/* Hour 07 cumulative enhancement: carrier detention discipline audit. */
function carrierDetentionDisciplineAudit(list=ranked()){
  const min=num(state.minDetentionDiscipline||72);
  return list.map(c=>{let score=Math.round(num(c.tracking)*0.38+num(c.onTime)*0.34+num(c.safety)*0.12+(c.status==='approved'?10:2)+Math.min(8,num(c.authorityMonths)/12)); if(c.fraud!=='none')score-=10; if((c.notes||'').toLowerCase().includes('tracking'))score+=4; score=Math.max(0,Math.min(100,score)); const blockers=[]; if(num(c.tracking)<82)blockers.push('weak timestamp/tracking confidence'); if(num(c.onTime)<82)blockers.push('appointment reliability risk'); if(c.status!=='approved')blockers.push('approval hold'); if(c.fraud!=='none')blockers.push('fraud/watch review'); const status=score>=min&&blockers.length===0?'detention-disciplined':score>=min-14?'document tightly':'detention risk'; return {...c,detentionScore:score,detentionStatus:status,detentionBlockers:blockers.length?blockers:['timestamp/POD discipline looks usable']};}).sort((a,b)=>a.detentionScore-b.detentionScore||b.score-a.score);
}
const __h7CarrierBaseBrief=buildBrief;
buildBrief=function(list=ranked()){const base=__h7CarrierBaseBrief(list); const audit=carrierDetentionDisciplineAudit(list); return base.replace('\n## Monetization angle', `\n## Carrier detention discipline\n${audit.map((a,i)=>`${i+1}. ${a.name}: ${a.detentionStatus}, score ${a.detentionScore}%, checks: ${a.detentionBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h7CarrierBaseRenderRankings=renderRankings;
renderRankings=function(){__h7CarrierBaseRenderRankings(); const audit=carrierDetentionDisciplineAudit(); const watch=audit.filter(a=>a.detentionStatus!=='detention-disciplined'); if($('detentionCarrierSummary'))$('detentionCarrierSummary').textContent=`${watch.length} document/risk · ${audit.length} carriers checked`; if($('detentionCarrierRows'))$('detentionCarrierRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.name}</h3><span class="pill ${a.detentionStatus==='detention-disciplined'?'good':a.detentionStatus==='document tightly'?'warn':'bad'}">${a.detentionScore}%</span><p>${a.detentionStatus}: ${a.detentionBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=buildBrief(); save();};
const __h7CarrierBaseRender=render;
render=function(){__h7CarrierBaseRender(); if(state.minDetentionDiscipline===undefined)state.minDetentionDiscipline=72; const ctl=$('minDetentionDiscipline'); if(ctl)ctl.value=state.minDetentionDiscipline;};
if(state.minDetentionDiscipline===undefined)state.minDetentionDiscipline=72;
const __h7CarrierDetentionCtl=$('minDetentionDiscipline'); if(__h7CarrierDetentionCtl)__h7CarrierDetentionCtl.addEventListener('input',()=>{state.minDetentionDiscipline=__h7CarrierDetentionCtl.value;save();renderRankings();});
$('downloadJson').onclick=()=>download('carrier-vetting-radar.json',JSON.stringify({controls:{...state},carriers:state.carriers,ranked:ranked(),blockerAudit:blockerAudit(),carrierPacketAudit:carrierPacketAudit(),carrierLifecycleSlaAudit:carrierLifecycleSlaAudit(),carrierDetentionDisciplineAudit:carrierDetentionDisciplineAudit(),brief:buildBrief(),safety:'local draft only'},null,2),'application/json');
/* Hour 08 cumulative enhancement: carrier appointment reliability audit. */
function carrierAppointmentReliabilityAudit(list=ranked()){return list.map(c=>{let score=Math.round(num(c.onTime)*0.42+num(c.tracking)*0.30+num(c.safety)*0.13+(c.status==='approved'?10:2)+Math.min(5,num(c.authorityMonths)/18)); if(c.fraud!=='none')score-=10; if(c.equipment!==state.equipment)score-=8; score=Math.max(0,Math.min(100,score)); const blockers=[]; if(num(c.onTime)<84)blockers.push('on-time risk'); if(num(c.tracking)<82)blockers.push('tracking/check-call risk'); if(c.status!=='approved')blockers.push('approval not final'); if(c.fraud!=='none')blockers.push('fraud/watch review'); const status=score>=78&&blockers.length===0?'appointment-reliable':score>=62?'confirm window':'appointment risk'; return {...c,appointmentReliabilityScore:score,appointmentReliabilityStatus:status,appointmentReliabilityBlockers:blockers.length?blockers:['appointment discipline usable for broker review']};}).sort((a,b)=>a.appointmentReliabilityScore-b.appointmentReliabilityScore||b.score-a.score);}
const __h8CarrierBaseBrief=buildBrief;
buildBrief=function(list=ranked()){const base=__h8CarrierBaseBrief(list); const audit=carrierAppointmentReliabilityAudit(list); return base.replace('\n## Monetization angle', `\n## Carrier appointment reliability\n${audit.map((a,i)=>`${i+1}. ${a.name}: ${a.appointmentReliabilityStatus}, score ${a.appointmentReliabilityScore}%, checks: ${a.appointmentReliabilityBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h8CarrierBaseRenderRankings=renderRankings;
renderRankings=function(){__h8CarrierBaseRenderRankings(); const audit=carrierAppointmentReliabilityAudit(); const watch=audit.filter(a=>a.appointmentReliabilityStatus!=='appointment-reliable'); if($('appointmentCarrierSummary'))$('appointmentCarrierSummary').textContent=`${watch.length} confirm/risk · ${audit.length} carriers checked`; if($('appointmentCarrierRows'))$('appointmentCarrierRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.name}</h3><span class="pill ${a.appointmentReliabilityStatus==='appointment-reliable'?'good':a.appointmentReliabilityStatus==='confirm window'?'warn':'bad'}">${a.appointmentReliabilityScore}%</span><p>${a.appointmentReliabilityStatus}: ${a.appointmentReliabilityBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=buildBrief(); save();};
$('downloadJson').onclick=()=>download('carrier-vetting-radar.json',JSON.stringify({controls:{...state},carriers:state.carriers,ranked:ranked(),blockerAudit:blockerAudit(),carrierPacketAudit:carrierPacketAudit(),carrierLifecycleSlaAudit:carrierLifecycleSlaAudit(),carrierDetentionDisciplineAudit:carrierDetentionDisciplineAudit(),carrierAppointmentReliabilityAudit:carrierAppointmentReliabilityAudit(),brief:buildBrief(),safety:'local draft only'},null,2),'application/json');

/* Hour 09 cumulative enhancement: carrier compliance expiry audit. */
function carrierComplianceExpiryAudit(list=ranked()){return list.map(c=>{let score=Math.round(num(c.insurance)*0.42+num(c.safety)*0.22+num(c.tracking)*0.12+Math.min(12,num(c.authorityMonths)/4)+(c.status==='approved'?10:2)); const blockers=[]; if(num(c.insurance)<num(state.minInsurance)){score-=18; blockers.push('insurance below threshold');} if(num(c.authorityMonths)<12){score-=12; blockers.push('new authority needs packet review');} if(c.status!=='approved'){score-=12; blockers.push('approval status not clean');} if(c.fraud!=='none'){score-=10; blockers.push('fraud/watch document check');} score=Math.max(0,Math.min(100,score)); const status=score>=80?'compliance-current':score>=62?'expiry watch':'compliance blocker'; return {...c,complianceExpiryScore:score,complianceExpiryStatus:status,complianceExpiryBlockers:blockers.length?blockers:['COI/W9/authority posture appears current for local review']};}).sort((a,b)=>a.complianceExpiryScore-b.complianceExpiryScore||b.score-a.score);}
const __h9CarrierBaseBrief=buildBrief;
buildBrief=function(list=ranked()){const base=__h9CarrierBaseBrief(list); const audit=carrierComplianceExpiryAudit(list); return base.replace('\n## Monetization angle', `\n## Carrier compliance expiry audit\n${audit.map((a,i)=>`${i+1}. ${a.name}: ${a.complianceExpiryStatus}, score ${a.complianceExpiryScore}%, checks: ${a.complianceExpiryBlockers.join('; ')}.`).join('\n')}\n\n## Monetization angle`);};
const __h9CarrierBaseRenderRankings=renderRankings;
renderRankings=function(){__h9CarrierBaseRenderRankings(); const audit=carrierComplianceExpiryAudit(); const watch=audit.filter(a=>a.complianceExpiryStatus!=='compliance-current'); if($('carrierComplianceSummary'))$('carrierComplianceSummary').textContent=`${watch.length} watch/blocker · ${audit.length} carriers checked`; if($('carrierComplianceRows'))$('carrierComplianceRows').innerHTML=audit.map(a=>`<article class="audit-card"><h3>${a.name}</h3><span class="pill ${a.complianceExpiryStatus==='compliance-current'?'good':a.complianceExpiryStatus==='expiry watch'?'warn':'bad'}">${a.complianceExpiryScore}%</span><p>${a.complianceExpiryStatus}: ${a.complianceExpiryBlockers.join('; ')}</p></article>`).join(''); if($('brief'))$('brief').value=buildBrief(); save();};
$('downloadJson').onclick=()=>download('carrier-vetting-radar.json',JSON.stringify({controls:{...state},carriers:state.carriers,ranked:ranked(),blockerAudit:blockerAudit(),carrierPacketAudit:carrierPacketAudit(),carrierLifecycleSlaAudit:carrierLifecycleSlaAudit(),carrierDetentionDisciplineAudit:carrierDetentionDisciplineAudit(),carrierAppointmentReliabilityAudit:carrierAppointmentReliabilityAudit(),carrierComplianceExpiryAudit:carrierComplianceExpiryAudit(),brief:buildBrief(),safety:'local draft only'},null,2),'application/json');

render();
